### ISSUE TITLE
Logic error in masterSymmetricKey handling

### ISSUE THREAD

**Issue by jagatfx** [awslabs/aws-lambda-redshift-loader#101]
The following code checks `if (!decryptedConfigItems[symmetricKeyMapEntry])`, or the symmetricKeyMapEntry property does not exist, but then goes and uses `decryptedConfigItems[symmetricKeyMapEntry]`. I think it should be `if (decryptedConfigItems[symmetricKeyMapEntry])` instead.

https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/index.js#L1342

```
                                    if (!decryptedConfigItems[symmetricKeyMapEntry]) {
                                        credentials = credentials
                                                + ";master_symmetric_key="
                                                + decryptedConfigItems[symmetricKeyMapEntry]
                                                        .toString();
                                    } else {
```

**Comment by IanMeyers** [comment]
Thanks - fixed in https://github.com/awslabs/aws-lambda-redshift-loader/commit/fbc1a7a8af2dd895e95674f06540af49fe8ff177
