### ISSUE TITLE
truncateTarget option removes statement_timeout

### ISSUE THREAD

**Issue by jagatfx** [awslabs/aws-lambda-redshift-loader#102]
When truncateTarget is used for the Redshift COPY query, the previously set timeout portion of the `copyCommand` set in https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/index.js#L1197 or https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/index.js#L1201 is removed. I do not think this was intentional. 

https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/index.js#L1208

```
        // add the truncate option if requested
        if (clusterInfo.truncateTarget && clusterInfo.truncateTarget.BOOL) {
            copyCommand = 'truncate table ' + clusterInfo.targetTable.S + ';\n';
        }
```

Instead, should use `copyCommand += 'truncate table ' + clusterInfo.targetTable.S + ';\n';`

**Comment by IanMeyers** [comment]
Thanks - fixed in https://github.com/awslabs/aws-lambda-redshift-loader/commit/fbc1a7a8af2dd895e95674f06540af49fe8ff177
