### ISSUE TITLE
clear LambdaRedshiftBatches table

### ISSUE THREAD

**Issue by stevesouders** [awslabs/aws-lambda-redshift-loader#106]
It's great having history in the LambdaRedshiftBatches and LambdaRedshiftProcessedFiles tables in DynamoDB, but after running for months with thousands of files every day, those tables are getting big. This makes them slow to query in the DynamoDB GUI. 

Is there a recommended way to clear out these tables? It would be great if there was an option to purge entries older than N days (similar to S3).

**Comment by IanMeyers** [comment]
Hello - sorry for the delay in coming back to you. There's nothing there today to do this. Will look into a utility script that will clear down batches older than X days, and then maybe let you have further control over the batch status as a filter too (aka keep anything in ERROR or whatever).

Would that suit you?

**Comment by stevesouders** [comment]
Sounds great!

**Comment by IanMeyers** [comment]
Please see the new `deleteBatches.js` utility in https://github.com/awslabs/aws-lambda-redshift-loader/commit/d6b4850d444c2c900f1bea855533946b906078bb, as well as updated README. Should do what you want now.
