### ISSUE TITLE
Enhancement: Support for redshift table data MERGE 

### ISSUE THREAD

**Issue by anurag77** [awslabs/aws-lambda-redshift-loader#108]
Hi,
I have been looking for a solution that has an 'UPSERT' equivalent built it. Like AWS data pipeline has the OVERWRITE_EXISTING write mode, would be possible to add a feature to handle duplicates while doing the load. Something on the lines of http://docs.aws.amazon.com/redshift/latest/dg/merge-replacing-existing-rows.html.

One of the biggest problems I am running into while using this tool is some of my tables get frequently updated and therefore the loader is adding a whole lot of duplicates, and I have to use a background cron job to remove them which is not ideal.

Thanks

**Comment by IanMeyers** [comment]
Thanks for the note. We get this required quite frequently, and the best way to implement this is to load a staging table, and then use Success SNS Notifications to trigger an AWS Lambda function that connects and does the transformation process.

Would that be an option for you?
