### ISSUE TITLE
"configure event source" doesn't exist

### ISSUE THREAD

**Issue by stevesouders** [awslabs/aws-lambda-redshift-loader#110]
Hi!

The Getting Started instructions say:

> On the deployed function, select Configure Event Source and select the bucket you want to use for input data. Ensure that you have selected 'Object Created' or the 'ObjectCreated:*' notification type.

But I think the UI has been changed, as it no longer says "Configure Event Source".

How do I setup the trigger for my Lambda function?

Thanks, Steve

**Comment by IanMeyers** [comment]
I've updated the readme now.

**Comment by stevesouders** [comment]
Makes sense. Thanks for clarifying!
