### ISSUE TITLE
Is lambda will run with less subnet IPs

### ISSUE THREAD

**Issue by AmitThakkar** [awslabs/aws-lambda-redshift-loader#111]
Can anyone tell me that, for moving data from S3 to Redshift we can use data pipeline too. Which one is better in between lambda & Data pipeline. And How Lambda is solving the problem below problem

Caution:
If your VPC does not have sufficient ENIs or subnet IPs, your Lambda function will not scale as requests increase, and you will see an increase in function failures.

**Comment by IanMeyers** [comment]
If your lambda functions are unable to allocate subnet IP's, then data pipeline will also fail as the EMR clusters that back pipeline instances will also be unable to allocate IP's, causing pipeline retries which will ultimately also fail.
