### ISSUE TITLE
Lambda is stuck

### ISSUE THREAD

**Issue by edtguy** [awslabs/aws-lambda-redshift-loader#116]
Forgive me if the following post is just newbie ignorance, but my installation of the Redshift loader is stuck, and I'm not sure how to get it going again.
I had finally gotten the process to read modified (i.e. remove surrounding array brackets and replace commas between objects with line feeds) json files copied into S3 and writing to the Redshift table.
Then starting yesterday, no copied files were being processed. Cloudwatch was reporting timeout after 3 seconds for each.
This morning, I changed the timeout on the Lambda function to 1 minute and restarted it.
Now, I see the following in Cloudwatch after each file is copied to S3:

`2017-03-14T15:45:21.780Z	356db6ba-08cd-11e7-bb6f-f76a086294a8	Unable to write [s3prefix/jsonFile] in 100 attempts. Failing further processing to Batch [batchId] which may be stuck in 'locked' state. If so, unlock the back using `node unlockBatch.js <batch ID>`, delete the processed file marker with `node processedFiles.js -d <filename>`, and then re-store the file in S3`

I tried following the above instructions, but the batch status is "reprocessed" not "locked". If I execute the reprocess script, it fails with retryable:false.

`[root aws-lambda-redshift-loader]# node describeBatch.js [region] [batchId] [s3prefix]
{"s3Prefix":{"S":"[s3prefix]"},"size":{"N":"3476"},"writeDates":{"NS":["1489416311.873"]},"status":{"S":"reprocessed"},"entries":{"SS":["[s3prefix]/loc27625-2017-03-13T10:00:00.json"]},"lastUpdate":{"N":"1489417684.938"},"batchId":{"S":"[batchId]"}}
[root aws-lambda-redshift-loader]# node reprocessBatch.js [region] [batchId] [s3prefix]
Submitted reprocess request for [s3prefix]/loc27625-2017-03-13T10:00:00.json
{"message":"The conditional request failed","code":"ConditionalCheckFailedException","time":"2017-03-14T16:14:54.876Z","requestId":"IGFC1C4I70FCLKLDS1F6B704HBVV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":false,"retryDelay":0}
[root aws-lambda-redshift-loader]#`

Any suggestions are most appreciated.

**Comment by IanMeyers** [comment]
Copy of email for external visibility:

Because the batch has been reprocessed (as shown by the describeBatch call), then the data should have been processed. The best way to confirm this is to check that it's in the processed files table.
 
Can you describeBatch on e6cb4dcb-b4e6-433b-9f4c-805bc5f97190 and let me know its status? Overall, I do recommend you set the function timeout to the maximum (5 minutes). You are only metered on what you consume, and it covers cases where there are queue waits holding up loads…

**Comment by edtguy** [comment]
Thank you Ian! 
As you had deduced, this batch was "stuck"  in the DynamoDB table, LambdaRedshiftBatchLoadConfig.
I downloaded the utility, resetCurrentBatch.js, that you just pushed, which resets the batch to a brand new one, and allow the loader to continue. Syntax:

`node resetCurrentBatch.js <your region> <your S3 prefix being loaded> <your current batch id>`

I'm back in business!
Cheers,
Ed
