### ISSUE TITLE
Setup hangs on encryption?

### ISSUE THREAD

**Issue by ulsa** [awslabs/aws-lambda-redshift-loader#12]
I got as far as the password question, and then the setup script seems to hang:

``` bash
$ AWS_REGION=eu-west-1 AWS_PROFILE=myprofile node setup.js
...
Enter the Database Password > somepwd
```

Something about the KMS encryption?

**Comment by ulsa** [comment]
Seems to work now. Stopped it, ran `export AWS_REGION=eu-west-1`, restarted as:

```
$ AWS_PROFILE=myprofile node setup.js
```

**Comment by IanMeyers** [comment]
Yes, will update the the documentation to specify better how to set the region for the setup.
