### ISSUE TITLE
No Configuration Found for <s3 path>

### ISSUE THREAD

**Issue by dollschasingmen** [awslabs/aws-lambda-redshift-loader#120]
Hi -- I am getting an error

```
No Configuration Found for lumos-data-dump-dev01/andy/prod/data
```

However, when I look in DynamoDb i see

![image](https://cloud.githubusercontent.com/assets/763803/25551224/8b676372-2c36-11e7-9963-72dd3bedd7de.png)

in table `LambdaRedshiftBatchLoadConfig`

Seems strange that the config could not be found considering it is right there, it matches the prefix exactly. Any suggestions on how to debug further? Thanks!

**Comment by dollschasingmen** [comment]
testing with a s3 put event that looks like this:

```
{
  "Records": [
    {
      "eventVersion": "2.0",
      "eventTime": "1970-01-01T00:00:00.000Z",
      "requestParameters": {
        "sourceIPAddress": "127.0.0.1"
      },
      "s3": {
        "configurationId": "testConfigRule",
        "object": {
          "eTag": "0123456789abcdef0123456789abcdef",
          "sequencer": "0A1B2C3D4E5F678901",
          "key": "andy/prod/data/HappyFace.jpg",
          "size": 1024
        },
        "bucket": {
          "arn": "arn:aws:s3:::lumos-data-dump-dev01",
          "name": "lumos-data-dump-dev01",
          "ownerIdentity": {
            "principalId": "EXAMPLE"
          }
        },
        "s3SchemaVersion": "1.0"
      },
      "responseElements": {
        "x-amz-id-2": "EXAMPLE123/5678abcdefghijklambdaisawesome/mnopqrstuvwxyzABCDEFGH",
        "x-amz-request-id": "EXAMPLE123456789"
      },
      "awsRegion": "us-east-1",
      "eventName": "ObjectCreated:Put",
      "userIdentity": {
        "principalId": "EXAMPLE"
      },
      "eventSource": "aws:s3"
    }
  ]
}
```

gives me the same result

```
No Configuration Found for lumos-data-dump-dev01/andy/prod/data
```

am i just missing something simple with the `filenameFilterRegex` ?

**Comment by IanMeyers** [comment]
Sorry to hear that. It does look like your configuration is correct, so there's clearly something going wrong. Can you try moving the `filenameFilterRegex` and retest? Also, if you can turn on debug on line 10:

`var debug = true;`

and then run the `build.sh` to create a new version you can deploy, we should get more information.

**Comment by dollschasingmen** [comment]
also for full disclosure this is AWSLambdaRedshiftLoader-2.4.6.zip

**Comment by dollschasingmen** [comment]
ok -- it looks like it was an access issue. which is weird, i copy and pasted the IAM json that is in the readme into the role. but i manually edited the role and got past this issue at the very least. it might be good if the error message was surfaced? Anyway closing.

**Comment by IanMeyers** [comment]
Added error logging and abort on no access condition - https://github.com/awslabs/aws-lambda-redshift-loader/commit/f7818ead08db3d3fa53fef568a91c5c8973f3b79
