### ISSUE TITLE
loader incorrectly requires batchTimeoutSecs in debug mode

### ISSUE THREAD

**Issue by dollschasingmen** [awslabs/aws-lambda-redshift-loader#121]
Well -- this is pretty edge case, but when debug is set to true, the following code

```
		if (config.batchTimeoutSecs && config.batchTimeoutSecs.N && pendingEntries.length > 0 && common.now() - batchCreateDate > parseInt(config.batchTimeoutSecs.N)) {
		    console.log("Batch age " + config.batchTimeoutSecs.N + " seconds reached");
		    doProcessBatch = true;
		} else {
		    if (debug === true) {
			console.log("Current batch age of " + (common.now() - batchCreateDate) + " seconds below batch timeout of " + config.batchTimeoutSecs.N);
		    }
		}
```

specifically logging line in the else clause, will throw an exception if `batchTimeoutSecs` is not in the config --
 which it doesn't have to be since it is not a required config.

**Comment by IanMeyers** [comment]
Fixed in https://github.com/awslabs/aws-lambda-redshift-loader/commit/1de35ce36853f020bbd70ae188b637b37d095ad2
