### ISSUE TITLE
Unable to load configuration using date subdirs

### ISSUE THREAD

**Issue by ulsa** [awslabs/aws-lambda-redshift-loader#13]
I have this structure on S3: `mybucket/logs/access/cdn/20150214/cdn_20150214_0001.log.gz`. I have tried various prefixes to account for the extra date directory, but without success. I now have this `s3Prefix` in the `LambdaRedshiftBatchLoadConfig` table:

```
mybucket/logs/access/cdn/*
```

I copy up a file:

```
aws s3 cp cdn_20150214_0001.log.gz s3://mybucket/logs/access/cdn/20150214/
```

I get this error in the CloudWatch Logs stream:

```
unable to load configuration for mybucket/logs/access/cdn/20150214
```

**Comment by ulsa** [comment]
Changed structure to be flat, and now I get passed this problem.

**Comment by IanMeyers** [comment]
You can use dynamic paths by specifying `<literal>=value` within the s3 prefix. This will then be translated to a configuration item of `<literal>=*` on lookup. For your example, if you can support an S3 path of `s3://mybucket/logs/access/cdn/dt=20150214`, then you would enter an S3 prefix configuration value of `s3://mybucket/logs/access/cdn/dt=*`
