### ISSUE TITLE
Some Gotchas 

### ISSUE THREAD

**Issue by alexsambacanada** [awslabs/aws-lambda-redshift-loader#131]
After hours of troubleshooting I have gotten this project to work successfully.  First off big thanks to everyone contributing!  I wanted to pass along some gotchas I ran into during the course of this setup that may save others in the long hours of troubleshooting I went through.  FYI I might just be dumb and this stuff may be common sense to other people.

1) **You try to run node setup.js and get an error about it not being able to find "node-uuid".**  node-uuid has been renamed to uuid so you will need to go into setup.js and change line 21 to "var uuid = require('uuid');" 

2) **Your lambda function does not trigger**. This is highly likely my incorrect interpretation of the walkthrough but during the setup.js process I selected my bucket prefix as bucket/prefix and did not select anything as a filter regex.  What ended up happening is is that S3 event notification was set to bucket/load/* (with the * at the end).  What I had to do was remove the * at the end and the trigger started firing.

3) **Cannot read property 'Attributes' of undefined**  If you get this error in your logs it is because there is some typos in the code that have yet to merged.  Make the changes specified here #130 

4) **LAMBDA in VPC cannot connect to Dynamo DB**.  You may not like the idea of setting a 0.0.0.0/0 allow rule in your redshift security group and decide to instead move lambda into the VPC.  Just know that YOU NEED the NAT gateway as specified in the walkthrough.  When Lambda goes into the VPC it gets assigned an ENI with a private IP and has no way of reaching outside (to talk to DynamoDB).  The traffic has to be natted.  Follow the network architecture from the guide and you should be fine.

5) **LAMBDA times out trying to connect to Redshift**.  In my scenario I had Lambda and Redshift in the SAME private subnet and the SAME security group.  Lambda could reach Dynamo and the outside world fine but could not connect to Redshift!  I changed the Redshift endpoint to the Redshift private IP with no luck, I disabled VPC DNS Resolution no luck.  I set an allow rule to the public IP of the NAT gateway into the redshift security group- no luck.  For some weird reason I cannot explain when I moved Lambda to its own security group (and created a rule allowing that group into the Redshift SG) it worked.  I have no idea what happened here.

6) Other pointers:  a)in the first couple lines of the code there is a debug option- set it to true and it gives you some additional information helpful for troubleshooting.  b) if you try to make a change to a DynamoDB table and get a red authorization error message, just re-sign in; session must be timing out.  c) the S3 folders for manifests and failed manifests get created for you, you don't need to create them ahead of time. 

Many of these are likely no brainers for others but thought I'd share anyway.

Thanks!

AlexW

**Comment by strias** [comment]
I don't think it was you on bullet 2. I tried in many ways and that * is always there.

**Comment by aseroj** [comment]
@alexsambacanada @IanMeyers  I am stuck at point 5 that you mentioned.
When the files are being uploaded into my S3 bucket the lambda gets triggered and it writes the batches inside DynamoDB as expected, but the manifests won't generate and it gets timeouts, and the writes into Redshift does not happen. here are the latest logs

```
14:10:59
2018-02-01T14:10:59.747Z	b9ef46a4-0759-11e8-81a0-e7fe706af191	Batch count 3 reached

14:10:59
2018-02-01T14:10:59.747Z	b9ef46a4-0759-11e8-81a0-e7fe706af191	Batch age 120 seconds reached

14:11:00
2018-02-01T14:11:00.018Z	b9ef46a4-0759-11e8-81a0-e7fe706af191	Creating Manifest for Batch f6bfc293-6e5d-4610-b87b-f7eb6f9bb7aa

14:11:00
2018-02-01T14:11:00.018Z	b9ef46a4-0759-11e8-81a0-e7fe706af191	Writing manifest to data-oz-manifest/manifest/manifest-2018-02-01 14:11:00-9385

14:11:58
END RequestId: b9ef46a4-0759-11e8-81a0-e7fe706af191

14:11:58
REPORT RequestId: b9ef46a4-0759-11e8-81a0-e7fe706af191	Duration: 60060.18 ms	Billed Duration: 60000 ms Memory Size: 128 MB	Max Memory Used: 39 MB

14:11:58
2018-02-01T14:11:58.939Z b9ef46a4-0759-11e8-81a0-e7fe706af191 Task timed out after 60.06 seconds
```


suggestions/recommendations are more than welcome

**Comment by IanMeyers** [comment]
Looks like you are hitting the lambda timeout. Try increasing this to 5 minutes?

**Comment by aseroj** [comment]
Thanks @IanMeyers , also tried 5 minutes, here is the output

```
21:40:47
REPORT RequestId: d88c762a-0797-11e8-8307-851ec2a37e4b	Duration: 300021.19 ms	Billed Duration: 300000 ms Memory Size: 128 MB	Max Memory Used: 42 MB

21:40:47
2018-02-01T21:40:47.183Z d88c762a-0797-11e8-8307-851ec2a37e4b Task timed out after 300.02 seconds
```

**Comment by mmeiman** [comment]
Hello all,

I know this is an old thread, but I am having a hard time get the loader working and thought maybe someone can help me here.

I setup the loader per the instructions and everything seems to be working except after dropping only ONE file into the bucket, the DynamoDb batch table gets flooded with items, and surprisingly all of them have the status  "Completed".

As a matter of fact unless I don't delete the Lambda function, new batches get created and completed continuously and new manifest files get generated and all of them have the same thing inside them: "Access Denied". 

I am suspicious that maybe the generation of the manifest file itself triggers the loader. This I can check easily.

HOWEVER the Access Denied part is very strange as I have provided the username and password of the user that can COPY the same file from the same s3 bucket into the same table with no issues.

Appreciate any help.

Cheers!

Mo

**Comment by IanMeyers** [comment]
Hello, 

That sounds like you have the same location set for the input prefix as well as the manifest files, which is resulting it continuously operating. You need to ensure that the manifest file location doesn't in the top level prefix. It's very odd that the manifest files contain the value 'Access Denied'. Can you send some example logs from cloudwatch?

Thx!

**Comment by mmeiman** [comment]
Hi Ian,

Thanks for the quick reply. Yes I believe the same thing, I will change the manifest prefix to get that resolved. As per the CloudWatch logs, I don't see anything any. Under the Logs there is /aws/lambda/LambdaRedshiftLoader Log Group but there are no streams inside this group.

Is there a setting I need to turn on? I checked the role and it has access to CloudWatch.

Cheers!

**Comment by mmeiman** [comment]
Ok I got the CloudWatch working and reviewing the logs exactly pointed out the issue. All fixed now.

Thanks for the fantastic work!

Mo
