### ISSUE TITLE
Lambda function is not running

### ISSUE THREAD

**Issue by yalba** [awslabs/aws-lambda-redshift-loader#134]
I've followed the steps to be able to load data into several redshift tables I created, using the lambda function in latest zip file, but for some reason the lambda function is not triggering. I looked at the S3 notification event configured and it looks good. I can't find anywhere any trail of what could be wrong. Disclosure: I'm new to AWS, so I might have easily overlooked something.
Any help would be appreciated.
Thanks.

**Comment by yalba** [comment]
I'm also getting this error when executing node setup.js
Table LambdaRedshiftBatchLoadConfig already exists
Creating S3 Event Source for s3://mckchcredshiftdatatest/part_files
c:\git\aws\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\request.js:31           
 throw err;
           ^
TypeError: Cannot read property 'AWS:SourceAccount' of undefined
    at c:\git\aws\aws-lambda-redshift-loader\common.js:441:67
    at Array.map (native)
    at Response.<anonymous> (c:\git\aws\aws-lambda-redshift-loader\common.js:438:17)
    at Request.<anonymous> (c:\git\aws\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\request.js:360:18)
    at Request.callListeners (c:\git\aws\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (c:\git\aws\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (c:\git\aws\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\request.js:673:14)
    at Request.transition (c:\git\aws\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (c:\git\aws\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at c:\git\aws\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\state_machine.js:26:10

**Comment by axiomoixa** [comment]
I have the same problem.
Using "test", the Lambda function runs properly and tables get loaded into Redshift, but when uploading files to S3, nothing gets triggered.

**Comment by IanMeyers** [comment]
Have you run the setup.js or setup-file.js script to create the event source mapping?

**Comment by axiomoixa** [comment]
Indeed,
`Event type: ObjectCreatedNotification name: LambdaRedshiftLoaderEventSource-040cce0a-0c08-46fa-a953-fc17292258afPrefix: /`

**Comment by IanMeyers** [comment]
OK - and in LambdaRedshiftBatchLoadConfig table in DynamoDB, do you see an Item for the bucket and prefix?

**Comment by axiomoixa** [comment]
yea, the s3Prefix shows the correct bucket name
Here is my config.json, with some sensitive fields replaced
> {
>         "region": "eu-west-1",
>         "s3Prefix": "*MYBUCKET*",
>         "filenameFilter": "",
>         "clusterEndpoint": "*MYREDSHIFT*",
>         "clusterPort": "5439",
>         "clusterUseSSL": "N",
>         "clusterDB": "dev",
>         "table": "*MYTABLE*",
>         "columnList": "",
>         "truncateTable": "N",
>         "userName": "*USER*",
>         "userPwd": "*PASSWORD*",
>         "df": "CSV",
>         "csvDelimiter": "\t",
>         "ignoreCsvHeader": "Y",
>         "jsonPaths": "",
>         "manifestBucket": "*ANOTHERBUCKET*",
>         "manifestPrefix": "manifest",
>         "failedManifestPrefix": "fail",
>         "accessKey": "",
>         "secretKey": "",
>         "successTopic": "",
>         "failureTopic": "",
>         "batchSize": "1",
>         "batchSizeBytes": "",
>         "batchTimeoutSecs": "120",
>         "copyOptions": "",
>         "symmetricKey": ""
> }
![image](https://user-images.githubusercontent.com/14837684/44583263-b2bce880-a7a4-11e8-8787-c5c2aaf350b9.png)

**Comment by axiomoixa** [comment]
Ok, figured that out.
prefix cannot be empty, which means one needs both bucket name and prefix

**Comment by jamalkhan** [comment]
Same issue. I've run the following:

```
{
    "region": "COUNTRY-REGION-1",
    "s3Prefix": "FIRST_BUCKET_NAME",
    "filenameFilter": "",
    "clusterEndpoint": "SOMECLUSTER.COUNTRY-REGION-1.redshift.amazonaws.com",
    "clusterPort": "5439",
    "clusterUseSSL": "N",
    "clusterDB": "DATABASE_NAME",
    "table": "SCHEMA_NAME.TABLE_NAME",
    "columnList": "",
    "truncateTable": "N",
    "userName": "USERNAME",
    "userPwd": "PASSWORD",
    "df": "JSON",
    "csvDelimiter": "\t",
    "ignoreCsvHeader": "Y",
    "jsonPaths": "FIRST_BUCKET_NAME/JSON_PATHS_FILE",
    "manifestBucket": "MANIFEST_BUCKET_NAME",
    "manifestPrefix": "redshift/copy/manifests/TABLE_NAME_manifest",
    "failedManifestPrefix": "redshift/copy/fails/TABLE_NAME",
    "accessKey": "",
    "secretKey": "",
    "successTopic": "",
    "failureTopic": "",
    "batchSize": "1",
    "batchSizeBytes": "",
    "batchTimeoutSecs": "120",
    "copyOptions": "",
    "symmetricKey": ""
}
```

I have Lambda + Firehose functions dropping data into FIRST_BUCKET_NAME in a Hive partition formatted date stamp, example, 2018 / 11 / 10 / 19 / NEW_UUID.

I want to open any file, and any corresponding data and drop it into this redshift table. I don't see any sign that this Lambda is firing. I don't see it in monitoring, I do see the configuration in the config tables in DynamoDB, but I don't see any batches.

Any help is greatly appreciated.

**Comment by jamalkhan** [comment]
> Same issue. I've run the following:
> 
> {
> "region": "COUNTRY-REGION-1",
> "s3Prefix": "FIRST_BUCKET_NAME",
> "filenameFilter": "",
> "clusterEndpoint": "SOMECLUSTER.COUNTRY-REGION-1.redshift.amazonaws.com",
> "clusterPort": "5439",
> "clusterUseSSL": "N",
> "clusterDB": "DATABASE_NAME",
> "table": "SCHEMA_NAME.TABLE_NAME",
> "columnList": "",
> "truncateTable": "N",
> "userName": "USERNAME",
> "userPwd": "PASSWORD",
> "df": "JSON",
> "csvDelimiter": "\t",
> "ignoreCsvHeader": "Y",
> "jsonPaths": "FIRST_BUCKET_NAME/JSON_PATHS_FILE",
> "manifestBucket": "MANIFEST_BUCKET_NAME",
> "manifestPrefix": "redshift/copy/manifests/TABLE_NAME_manifest",
> "failedManifestPrefix": "redshift/copy/fails/TABLE_NAME",
> "accessKey": "",
> "secretKey": "",
> "successTopic": "",
> "failureTopic": "",
> "batchSize": "1",
> "batchSizeBytes": "",
> "batchTimeoutSecs": "120",
> "copyOptions": "",
> "symmetricKey": ""
> }
> 
> I have Lambda + Firehose functions dropping data into FIRST_BUCKET_NAME in a Hive partition formatted date stamp, example, 2018 / 11 / 10 / 19 / NEW_UUID.
> 
> I want to open any file, and any corresponding data and drop it into this redshift table. I don't see any sign that this Lambda is firing. I don't see it in monitoring, I do see the configuration in the config tables in DynamoDB, but I don't see any batches.
> 
> Any help is greatly appreciated.

Making progress. "s3Prefix": "FIRST_BUCKET_NAME",

Bucket Name is "Zio-Category-View". Moving forward with "Zio-Category-View/2018", but as mentioned above, the Hive partition formatted date stamp is going to cause me problems when 2019 comes. I've tried all combinations of wildcards, but I can't get it to respond to things like...

```
Zio-Category-View/*
Zio-Category-View/*/*/*/*
```

etc.

 I'm open to suggestions.

**Comment by IanMeyers** [comment]
So today the requirement is that the layout of the S3 bucket is fixed for any one configuration of the loader, and does require that you use [Hive Dynamic Partitioning](https://cwiki.apache.org/confluence/display/Hive/DynamicPartitions) structure - in the form of 'partition_column=partition_value'. Given this, your s3 bucket needs to be structured as `yyyy=2018/MM=11/DD=10/HH=19/...` for the loader to work correctly. Given your use case, I would propose that instead of using this function, you simply allow Firehose to load Redshift for you, which will avoid this issue. Is that an option?
