### ISSUE TITLE
Typo in Module Name

### ISSUE THREAD

**Issue by watchwithmike** [awslabs/aws-lambda-redshift-loader#136]
https://github.com/awslabs/aws-lambda-redshift-loader/blob/42cb409c244a5f556139c68fb932e94bff5c488e/kmsCrypto.js#L21

The module name contains `Lamba` instead of Lamb**d**a, was this done on porpoise?

Discovery and pun by @wwswaziloo while working on our key rotation.

**Comment by IanMeyers** [comment]
Nope, that's just a typo. I'll have to update and then build a new module to prevent existing deployments from breaking. Sad Face :(
