### ISSUE TITLE
lambda function stuck at kmsCrypto.decryptMap

### ISSUE THREAD

**Issue by reghubalan** [awslabs/aws-lambda-redshift-loader#137]
In my case, since the lambda is running in the VPC, I have tried following all the instructions provided here to create NAT Gateway that routes the private subnets that the Lambda connects to the internet gateway by the route tables. I also have a separate security group for lambda and  added the inbound rule to the redshift security group for this lambda-sg. Going by the resolved issues here, I found that a few people could get this issue resolved by following these steps, but I am encountering timeout issues. 

Can anyone please provide some assistance on what else to check and how to move forward to get this resolved?

**Comment by IanMeyers** [comment]
Please email me at meyersi@amazon.com and we'll go through your configuration to try and debug it.
