### ISSUE TITLE
Lambda function does not trigger

### ISSUE THREAD

**Issue by ndorge** [awslabs/aws-lambda-redshift-loader#138]
I have followed the steps and  when I did node setup.js my dynamo tables are created, S3 even source gets created and it granted S3 permission to invoke my lambda function. When i upload a CSV file to my bucket I expect the lambda function to trigger but it does not.

I then realized that I might have missed some steps related to NAT and I repeated my setup. This time when I run node setup.js, it said that the tables are already created, it created the S3 event source and this time it says "Found existing Policy match for S3 path to invoke LambdaRedshiftLoader". Uploaded my file to the bucket but Lambda function still doesnt get triggered.

I am inexperienced with NAT so not sure if I have done the setup correctly. Any help with resolving this would be highly appreciated.

**Comment by IanMeyers** [comment]
Can you check the contents of the DynamoDB LambdaRedshiftBatchConfig table and let me know if there's anything in it? If not, can you rerun setup.js and ensure that a configuration is placed into this table?
