### ISSUE TITLE
Running reprocessBatch.js replaces s3 object metadata

### ISSUE THREAD

**Issue by garithd** [awslabs/aws-lambda-redshift-loader#143]
When using encryption on the S3 object 'reprocessBatch.js' replaces the Metadata which includes the envelope encryption key which means the file cannot be un-encrypted by Redshift COPY.

The MetadataDirective : "REPLACE" causes this bug.
The other option over here: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/MetadataDirective.html is "COPY" which causes an error if used:

{"message":"This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.","code":"InvalidRequest","region":null,"time":"xxxxxxxxxxxxxx}

One way would be to read the s3 object metadata in first and then replace all the metadata and then appending:

CopyReason : "AWS Lambda Redshift Loader Reprocess Batch " + thisBatchId

**Comment by IanMeyers** [comment]
Yikes v sorry for this. Working on it now!

**Comment by IanMeyers** [comment]
I've pushed a fix for this in https://github.com/awslabs/aws-lambda-redshift-loader/commit/a8548098e24df47116880763df917d142cf7d3df

**Comment by garithd** [comment]
Thanks Ian, working like a charm now. I see the original encryption data and the appended "x-amz-meta-copyreason" : "Reprocessed..." metatdata. Closing.
