### ISSUE TITLE
If a manifest file contains file that fail to load, the entire batch fails to load

### ISSUE THREAD

**Issue by frankfarrell** [awslabs/aws-lambda-redshift-loader#146]
We had some stray locked files from before our redshift schema changed. When we unlocked these it tried to load them in the same batches as more recent files that conformed to the schema change. This meant that the entire batch failed to load. 

For example the manifest file that failed looked something like this: 

    {
            "entries": [{
                  "url": "s3://old1.csv",
                  "mandatory": true
              }, {
                  "url": "s3://old2.csv",
                  "mandatory": true
               }, {
                   "url": "s3://new.csv",
                  "mandatory": true
             }
        ]
    }

Old1.csv and old2.csv contains malformed entries, so of course we don't expect any magic with those. But how could ensure new.csv is loaded in this case?

Could the redshift loader demultiplex these failed batches and retry one by one for best effort?
I know this is essentially a quirk of how the redshift COPY command works, but I think it would be handy to work around it (as firehose seems to)

Thanks

**Comment by IanMeyers** [comment]
Hrm - good point. I'd suggest that you edit the entries value in the DDB table and then use the reprocessBatch.js script to resubmit the batch for processing. Can you try that and let me know?

**Comment by frankfarrell** [comment]
Ok, thanks for the idea. We can try that. How hard would it be to do this programatically? I can submit a PR

**Comment by IanMeyers** [comment]
If you know that a file in a batch is bad, then I can definitely see value in a 'minus-file' argument to the reprocess batch script.

**Comment by IanMeyers** [comment]
This is now supported from 3d49708.
