### ISSUE TITLE
Strict string comparison between clusterInfo.useSSL.BOOL (boolean) and string literal 'true'

### ISSUE THREAD

**Issue by ItsWayneYang** [awslabs/aws-lambda-redshift-loader#151]
Version:  2.5.5
Code:  Line 1171 of index.js
Problem:  Setting `clusterUseSSL` to `Y` in config.json has no effect because strict string comparison is used to check that boolean config value.

**Comment by IanMeyers** [comment]
I believe this is resolved in 2.6.2.

**Comment by IanMeyers** [comment]
What is the value in the configuration? You should see a 'true' as the setup.js configures the value to be a BOOL
