### ISSUE TITLE
Copy with dimension id fk lookups?

### ISSUE THREAD

**Issue by NickKellett** [awslabs/aws-lambda-redshift-loader#154]
I already have a SQL script that can COPY new facts. As part of the copy process, it's got additional code to lookup the various dimension foreign keys (for date, time, etc). I'd like to use this loader to handle the intake so it can avoid re-trying all the files that have previously been loaded from my S3 buckets. But there doesn't seem to be an obvious setting for doing anything more than a basic COPY (unless I'm misunderstanding). Is there a recommended way to customize Lambda Loader so I can include upsert and dimension lookup SQL code (ex. modify index.js)?

**Comment by IanMeyers** [comment]
Hello,

The best way to do this is to configure a success SNS Topic, and then process the events that are raised for successful loads using the tool of your choice.
