### ISSUE TITLE
ConditionalCheckFailedException while trying to update RedshiftBatchLoadConfig.

### ISSUE THREAD

**Issue by davinchia** [awslabs/aws-lambda-redshift-loader#156]
First, let me say this has been working great for the last few months. Recently, we have been looking into tuning some of the parameters in the configuration file in the `RedshiftBatchLoadConfig` table. Specifically, we wanted to experiment with the `batchSize` flag. We were previously able to modify this when the lambda was invoked relatively few times a minute (< 10/min), but are unable to do so when the lambda is being invoked multiple times a minute (>100/min), with updates via the console resulting in a `ConditionalCheckFailedException`. 

From, 
https://stackoverflow.com/questions/40037719/updating-dynamodb-from-dashboard-getting-conditionalcheckfailedexception, it seems the object cannot be modified because it is been too frequently read. This seemed to be the case as we were able to change the flag after throttling the function. Increasing the provisioned read capacity had no effect. 

For context, the tables involved with the lambda loader have virgin configurations - with the default 5 provisioned read and write capacity, and nothing else changed or enabled e.g. autoscaling, logging etc. Something else confusing is the mismatch between the table's `ConsumedReadCapacity` and our current provisioned read capacity. CloudWatch shows something closer to 700 units, while our current capacity is 5. Does the loader do anything funky under the hood?

Is there a 'best practices' way to do change configuration? Its unwieldy, and even dangerous, to only be able to update configurations when the lambda is not being heavily utilised. Perhaps, shifting flags we want to frequently update into lambda environment variables?

**Comment by IanMeyers** [comment]
Hello - I understand the issue, and this is actually not down to the implementation of the codebase, but rather to the implementation of the DynamoDB Console. What we need is an update-parameter function that will programmatically update the configuration for a prefix and value, with retry in case of these conditions. I will look at that asap.

**Comment by davinchia** [comment]
Excellent. That would be very much appreciated! Thanks Ian!

Do you have any insight into the big mismatch between provisioned capacity, and consumed capacity? Its not a big issue - am merely curious.

**Comment by IanMeyers** [comment]
Just shipped 0805384 with updateConfig.js and common.updateConfig() for performing this action.

What do you mean by mismatch between provisioned and consumed capacity?
