### ISSUE TITLE
Ability to specify Time Format string in config

### ISSUE THREAD

**Issue by joelhess** [awslabs/aws-lambda-redshift-loader#165]
I just need to be able to specify a time format as part of the copy command. I could either specify the specific format string, or my case seems to work with `TIMEFORMAT 'auto'`

**Comment by IanMeyers** [comment]
You should be able to add this to the 'other copy options' part of the configuration. Can you try configuring this during the setup?

**Comment by joelhess** [comment]
That worked. Thanks for the suggestion!
