### ISSUE TITLE
[Feature Request] Add triggering of external lambda function post successful Redshift Load

### ISSUE THREAD

**Issue by seb-steuer** [awslabs/aws-lambda-redshift-loader#166]
Hi,

I think it would be a nice to have feature when a successful load to RedShift could trigger external custom lambda function if configured.

This could potentially be used for initiating some transformations or external processing or whatever one can come up with as needed with such lambda.

kind regards
Sebastian

**Comment by IanMeyers** [comment]
Yep - you can do this today. Setup an SNS Topic, and then register the arn as the success notification topic in the configuration, and then you can create new Lambda workflows based on those triggers.

**Comment by seb-steuer** [comment]
You're right, I've missed the successTopicARN
Great, thanks
