### ISSUE TITLE
Password encryption for config items

### ISSUE THREAD

**Issue by seb-steuer** [awslabs/aws-lambda-redshift-loader#167]
Hi,

I'm working on a project that I want to fully deploy using CloudFormation.
The aim is to have entire environment fully functional after CFormation deployment.
I'm using redshift loader as one of the components in that project. I've captured all resources that setup creates and their relationships and turned it into parameterized CFormation template and I've got it fully working for quite a while now. One thing that I'm unable to do is a config generator using CFormation custom resource driven by lambda written in python. I can't sort the encrypted password bit.
Every time I supply an encrypted PW using the same KMS key redshift loader setup is using redshift loader won't work. So I'm forced to run through setup at least once to grab the encrypted PW string.

This bit of code represents what I'm using to get my encrypted PW I want to use with config items:

```
import boto3
import base64

kms = boto3.client('kms',region_name='us-west-2')

key_id = 'arn:aws:kms:us-west-2:XXXXXXXXXXXX:key/XXXXXXXX-XXXX-XXXXX-XXXX-XXXXXXXXXXXX'
stuff = kms.encrypt(KeyId=key_id, Plaintext='SECRETPW')
binary_encrypted = stuff[u'CiphertextBlob']
encrypted_password = base64.b64encode(binary_encrypted)
print(encrypted_password.decode())
```

Is there anything obvious I'm missing?

kind regards

**Comment by IanMeyers** [comment]
Can you have a look at how the setup-file.js script works? This enables you to provide a configuration file. We may need to refine how it treats passwords in this step.

Thx,

Ian

**Comment by seb-steuer** [comment]
I dont know JS but isn't setup-file.js also calling common.setup that ise responsible for setting up dynamodb table and s3 events?

I wouldn't want that to happen, my DDB tables are created by CFormation with capacity calculated depending on workers number parameter and their size I decide to have and S3 events are also handled by CFormation.

I'm looking into only writing the config item in DDB without touching anything else. I maybe read this the wrong way but is that possible somehow with setup-file.js?

**Comment by seb-steuer** [comment]
Ok from the kmsCrypto.js i see that I'm missing EncryptionContext for my kms.decrypt. And you put it together using authContext variable.

I'll play with that and post my findings here in case somebody finds it useful

**Comment by seb-steuer** [comment]
Works!

```
import boto3
import base64

kms = boto3.client('kms',region_name='us-west-2')

key_id = 'arn:aws:kms:us-west-2:XXXXXXXXXXXX:key/XXXXXXXX-XXXX-XXXXX-XXXX-XXXXXXXXXXXX'
encryptionContext={ "module" : "AWSLambdaRedshiftLoader", "region" : "us-west-2" }
stuff = kms.encrypt(KeyId=key_id, Plaintext='SECRETPWTOENCRYPT', EncryptionContext=encryptionContext)
binary_encrypted = stuff[u'CiphertextBlob']
encrypted_password = base64.b64encode(binary_encrypted)
print(encrypted_password.decode())
```
