### ISSUE TITLE
Large files ignored

### ISSUE THREAD

**Issue by ulsa** [awslabs/aws-lambda-redshift-loader#17]
Smaller files (~5 MB) are recognised, but as soon as I upload a 50 MB file, the system turns silent. No batch is created, no log stream. Is it because the lambda fails? Too little memory allocated? Why isn't a log stream created anyway?

**Comment by IanMeyers** [comment]
If you could email me at meyersi@Amazon.com we can take these out of github and get you moving forward.

**Comment by narendramaruti** [comment]
Hi Meyers, i hit this same issue in one of the Lambda i created. Can you please suggest me the fix.

**Comment by IanMeyers** [comment]
Can you check if the Event Source mapping is setup to be `s3:ObjectCreated:Put`. If so this could be the cause, in that many S3 clients will use multi-part uploads if the file is larger than 8MB. If this is how it's configured, please update the Event Source Mapping to be `s3:ObjectCreated:*`

**Comment by narendramaruti** [comment]
Thanks Meyers. Yes you are correct. it was using only` Put` trigger. I changed to `All` and it is working fine.
