### ISSUE TITLE
DynamoDB Provisioned Capacity Tuning/Planning

### ISSUE THREAD

**Issue by joelhess** [awslabs/aws-lambda-redshift-loader#170]
I'm trying to use this for processing a stream of small files (~1kb) that come in a pretty burst-y rate, but I keep bumping into Capacity issues with Dynamo. Specifically with trying to add a file to a batch. I keep bumping up the capacity units on the batch table, but I keep hitting the threshold when there's more than a few files coming in per second. Is there any recommendations for how to tune the capacity units, and/or should I even be using this for this type of stream processing?

**Comment by IanMeyers** [comment]
Hello,

Have you considered turning on DynamoDB Autoscaling? This should result in your capacity ramping up to just the right level for these tables to deal with the demand that the loader is placing on them. A very large number of small files isn't a great model for loading the database, as the % of time spent transferring a file will be very large relative to the amount of time spent loading. And, as you've seen, the amount of capacity you have to allocate to deal with the coordination rate. Is it possible to increase the size of the files and reduce the frequency?

Thx,

Ian
