### ISSUE TITLE
I can't get the lambda to be called

### ISSUE THREAD

**Issue by bram70** [awslabs/aws-lambda-redshift-loader#171]
I'm debugging the lambda I uploaded, I am doing console.log("HELLO") inside the handler function.
My function never get's called.
Is it an issue with the S3 Prefix for Redshift COPY Manifests? or S3 Bucket for Redshift COPY Manifests?
If so, what would you advice to have a pattern as follows:
```
FILENAME-2018-08-16T2105HASH.csv
Where 21 is 21:00 and 05 minutes
HASH is any random hash string.
```

Thanks for your support.

UPDATE:
 I'm getting this following error:
```
InvalidArgument: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.
```
Not sure if `Enter the Prefix to use for Failed Load Manifest Storage (must differ from the initial manifest path)` it's causing me issues.

**Comment by joelhess** [comment]
I've seen this when you try to setup the lambda, and there's already an S3 trigger created that covers the pattern that you're looking for.

**Comment by bram70** [comment]
@joelhess I got to fix the issue related to the `Configuration is ambiguously defined`
But my lambda function doesn't get called yet. I upload a file into the s3 bucket, I have a really opened suffix, (*.csv) , and I don't see my lambda to be called in the logs. The event in the s3 bucket has the `ObjectCreate (All)` Event checked, and it indeed has the role permission to read from S3.
Any advice here?

**Comment by bram70** [comment]
nevermind. I found the cause.
It was my preffix, and suffix which were messing up.

Sorry about this silly issue.
Best
