### ISSUE TITLE
Support UPSERT functionality

### ISSUE THREAD

**Issue by pkudinov** [awslabs/aws-lambda-redshift-loader#172]
This functionality can replace the need in Data Pipeline in it's most basic use:
Given that target table has primary key columns, perform update or insert rows to that table using temporary table with join.

Could there be any other requirements for this?

**Comment by IanMeyers** [comment]
Hello,

I'll and an FAQ section to the docs, as we get this type of request a lot. Unfortunately, I don't want to extend this codebase to be an ETL engine, but rather just as a pure play loader, and then support downstream capability to build ETL's. As such, I would advise that you use the success and failure notifications feature, which will allow you to:

* Load a temporary table
* Receive the success notification from SNS Topic
* Implement a Lambda function, AWS Glue Job, or other type of ETL process to manage the upsert
* Cleanup the temporary table

Hopefully that makes sense and will work for you.

Thanks,

Ian
