### ISSUE TITLE
TypeError: Cannot read property 'Attributes' of undefined

### ISSUE THREAD

**Issue by jagilbert27** [awslabs/aws-lambda-redshift-loader#175]
Hi,
I'm setting up the LambdaRedshiftLoader for the first time and getting this error in the log stream when the lambda is triggered:
```
TypeError: Cannot read property 'Attributes' of undefined
at /var/task/index.js:681:17
at /var/task/common.js:200:2
at /var/task/node_modules/async/dist/async.js:906:16
at next (/var/task/node_modules/async/dist/async.js:5175:18)
at Response.<anonymous> (/var/task/common.js:191:7)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
```
I see that others have had that issue a year ago, and it was fixed by installing a later version.  I pulled the latest version several weeks ago, but not sure what version I have.

`aws s3 ls`
Correctly returns all my bucket names.  This means I have a successful connection to aws

`node queryBatches --region us-east-1 --batchStatus locked`
Echos the query that is sent to dynamo, but hangs > 5 mins.  I killed it.

`node unlockBatch.js us-east-1 4b635a39-7e6c-4483-a254-75cd829ea88d BRANDSCS/RedshiftStage/`
Hangs, no response

After that error, there is one record in the LambdaRedshiftBatches table.  It's status=locked.
If I delete the items in the LambdaRedshiftBatches and LambdaRedshiftProcessedFiles
 tables and re-trigger the lambda, the results are the same.
If I re-trigger the lambda without resetting, I get different errors, but that is not surprising because the LambdaRedshiftBatchLoadConfig.currentBatch is orphaned.

Cheers,
Jeff Gilbert

**Comment by jagilbert27** [comment]
Update:  The reason that the queryBatches and the unlockBatch scripts hung was that my local proxy in my test environment was blocking the connection (Doh).  Those scripts now perform as expected.  

But the main problem remains:  "TypeError: Cannot read property 'Attributes' of undefined at /var/task/index.js:681:17

I'm not confident in the syntax and location of my manifest file.

**Comment by IanMeyers** [comment]
Looking into this now

**Comment by IanMeyers** [comment]
I can confirm that the issue is that you have version 2.5.0 deployed, which is due to a documentation bug where the latest versions were not being correctly cited. This documentation has now been updated, and I would request that you follow the [README](https://github.com/awslabs/aws-lambda-redshift-loader#getting-started---deploying-the-aws-lambda-function) instructions in section "Getting Started - Deploying the AWS Lambda Function" to ensure that you have version 2.6.5 deployed, where this issue is no longer found. I do apologise for the time that this has wasted, and have added a project TODO to move the deployment process to use [AWS SAM](https://github.com/awslabs/serverless-application-model) instead of hand deployment.

**Comment by jagilbert27** [comment]
Thanks Ian,

I uploaded AWSLambdaRedshiftLoader-2.6.5.zip and I am not getting that error anymore.
Now I get `Adding Pending Batch Entry for myfile.csv` in the cloudwatch log when I upload a file.

I doesn't seem to be loading the file though.  I think the batch criteria are met.  From LambdaRedshiftBatchLoadConfig: `"batchSize": 1,  "batchSizeBytes": 1000,  "batchTimeoutSecs": 10,...  "version": "2.6.5"`

If I directly change values in LambdaRedshiftBatchLoadConfig, do I need to do anything to activate them?

**Comment by IanMeyers** [comment]
That's great. Can you please drop the whole log stream entry set for the last invocation?

**Comment by jagilbert27** [comment]
When the Lambda is triggered, I get 
`Adding Pending Batch Entry for myfile.csv`
then it does this repeatedly until it reaches the lambda timeout:
`still current after configuration reload attempt 1. Recycling in 0 ms.`
...
`still current after configuration reload attempt 65. Recycling in 42250 ms.`
I'll upload that log stream in a sec

**Comment by IanMeyers** [comment]
Ah ok. That's because the open batch is locked and it's waiting for it to transition out to error status. If you use the unlockBatch.js script you should be able to set it back to 'pending'.

**Comment by jagilbert27** [comment]
Excellent, will do...

**Comment by IanMeyers** [comment]
Also could you kindly redeploy 2.6.5 from s3? Your log message demonstrated that there's a timeout issue in this condition that I've now fixed.

**Comment by jagilbert27** [comment]
Glad to.
(sry, Where is the that fixed version?)

**Comment by jagilbert27** [comment]
pulling AWSLambdaRedshiftLoader-2.6.5.zip from commt: 45f6006

**Comment by jagilbert27** [comment]
I uploaded new source to my LambdaRedshiftLoader from the AWSLambdaRedshiftLoader-2.6.5.zip from commit 45f6006.  I deleted the three Dynamo tables, and re-executed node setup.js.

I now get this error when the lambda is triggered:
`"{\"redshift-cdr.cc5mfylzdhpr.us-east-1.redshift.amazonaws.com\":{\"status\":-1,\"error\":{\"name\":\"error\",\"length\":144,\"severity\":\"FATAL\",\"code\":\"3D000\",\"file\":\"/home/ec2-user/padb/src/pg/src/backend/utils/init/postinit.c\",\"line\":\"401\",\"routine\":\"InitPostgres\"}}}"`

Here's the whole record:
```{
  "batchId": {
    "S": "dc4bae6e-dcf2-4967-9d09-aed7fa949746"
  },
  "clusterLoadStatus": {
    "S": "{\"redshift-cdr.cc5mfylzdhpr.us-east-1.redshift.amazonaws.com\":{\"status\":-1,\"error\":{\"name\":\"error\",\"length\":144,\"severity\":\"FATAL\",\"code\":\"3D000\",\"file\":\"/home/ec2-user/padb/src/pg/src/backend/utils/init/postinit.c\",\"line\":\"401\",\"routine\":\"InitPostgres\"}}}"
  },
  "entries": {
    "SS": [
      "usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftStage/2018/11/00/out_call.csv.CITICARD_DET_18-11-01_00-20_zv1.part_00000"
    ]
  },
  "errorMessage": {
    "S": "{\"redshift-cdr.cc5mfylzdhpr.us-east-1.redshift.amazonaws.com\":{\"status\":-1,\"error\":{\"name\":\"error\",\"length\":144,\"severity\":\"FATAL\",\"code\":\"3D000\",\"file\":\"/home/ec2-user/padb/src/pg/src/backend/utils/init/postinit.c\",\"line\":\"401\",\"routine\":\"InitPostgres\"}}}"
  },
  "lastUpdate": {
    "N": "1542301408.664"
  },
  "manifestFile": {
    "S": "usan-insight-ingestion-0011-ctg/usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftLoader/FailedManifests/manifest-2018-11-15 17:03:28-6489"
  },
  "s3Prefix": {
    "S": "usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftStage"
  },
  "size": {
    "N": "242570"
  },
  "status": {
    "S": "error"
  },
  "writeDates": {
    "NS": [
      "1542301407.963"
    ]
  }
}
```

**LambdaRedshiftBatchLoadConfig**
```{
  "batchSize": 1,
  "batchSizeBytes": 1000,
  "batchTimeoutSecs": 10,
  "csvDelimiter": ",",
  "currentBatch": "635b1b8b-34bb-4c49-a27d-99d666ff9e3a",
  "dataFormat": "CSV",
  "failedManifestKey": "usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftLoader/FailedManifests",
  "failureTopicARN": "arn:aws:sns:us-east-1:642128000137:RedshiftDataLoaderSnsTopic",
  "ignoreCsvHeader": false,
  "lastBatchRotation": "2018-11-15 17:03:28",
  "loadClusters": [
    {
      "clusterDB": "dev.test_insight",
      "clusterEndpoint": "redshift-cdr.cc5mfylzdhpr.us-east-1.redshift.amazonaws.com",
      "clusterPort": 5439,
      "connectPassword": "AQICAHjRiM1ymILsYnr6D/NhksZWS4lQB3HodKnnoy3NcNzmrgEssnc4UJJC+kd5aaysfC9hAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7/2ALbMK3VuCqEpBAgEQgCQeRN7aG9qmJm8bN2BAc6eKXUCcUJBXY6NMdBBqqn7EB8Dbc0o=",
      "connectUser": "jg",
      "targetTable": "zstage_call",
      "truncateTarget": false,
      "useSSL": true
    }
  ],
  "manifestBucket": "usan-insight-ingestion-0011-ctg",
  "manifestKey": "BRANDSCS/RedshiftLoader/ImportManifests",
  "s3Prefix": "usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftStage",
  "successTopicARN": "arn:aws:sns:us-east-1:642128000137:RedshiftDataLoaderSnsTopic",
  "version": "2.6.5"
}
```

Cheers,
Jeff

**Comment by jagilbert27** [comment]
On further inspection, apparently I've specified the db name incorrectly.  How do I specify the db and schema containing the table to load?  

Here is the log of one invocation:
```START RequestId: 3d676db8-e8f5-11e8-a135-6b356668319a Version: $LATEST
2018-11-15T16:41:06.182Z	3d676db8-e8f5-11e8-a135-6b356668319a	Found Redshift Load Configuration for usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftStage
2018-11-15T16:41:06.386Z	3d676db8-e8f5-11e8-a135-6b356668319a	Adding Pending Batch Entry for usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftStage/FailedManifests/manifest-2018-11-15+16:41:01-6874
2018-11-15T16:41:06.664Z	3d676db8-e8f5-11e8-a135-6b356668319a	Batch count 1 reached
2018-11-15T16:41:06.847Z	3d676db8-e8f5-11e8-a135-6b356668319a	Creating Manifest for Batch 5eeb7824-e978-4a4d-9bfd-a67c62eafe5c
2018-11-15T16:41:06.848Z	3d676db8-e8f5-11e8-a135-6b356668319a	Writing manifest to usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftStage/Manifests/manifest-2018-11-15 16:41:06-8246
2018-11-15T16:41:07.156Z	3d676db8-e8f5-11e8-a135-6b356668319a	Created Manifest usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftStage/Manifests/manifest-2018-11-15 16:41:06-8246 Successfully
2018-11-15T16:41:07.183Z	3d676db8-e8f5-11e8-a135-6b356668319a	Loading 1 Clusters
2018-11-15T16:41:07.362Z	3d676db8-e8f5-11e8-a135-6b356668319a	Linked Manifest manifest-2018-11-15 16:41:06-8246 to Batch 5eeb7824-e978-4a4d-9bfd-a67c62eafe5c
2018-11-15T16:41:07.403Z	3d676db8-e8f5-11e8-a135-6b356668319a	Connecting to Database redshift-cdr.cc5mfylzdhpr.us-east-1.redshift.amazonaws.com:5439
2018-11-15T16:41:07.762Z	3d676db8-e8f5-11e8-a135-6b356668319a	Cluster Load Failure error: database "dev.test_insight" does not exist on Cluster redshift-cdr.cc5mfylzdhpr.us-east-1.redshift.amazonaws.com
2018-11-15T16:41:07.886Z	3d676db8-e8f5-11e8-a135-6b356668319a	Failing Batch 5eeb7824-e978-4a4d-9bfd-a67c62eafe5c due to [object Object]
2018-11-15T16:41:08.262Z	3d676db8-e8f5-11e8-a135-6b356668319a	Created new Failed Manifest usan-insight-ingestion-0011-ctg/BRANDSCS/RedshiftStage/FailedManifests/manifest-2018-11-15 16:41:06-8246
2018-11-15T16:41:08.666Z	3d676db8-e8f5-11e8-a135-6b356668319a
{
    "redshift-cdr.cc5mfylzdhpr.us-east-1.redshift.amazonaws.com": {
        "status": -1,
        "error": {
            "name": "error",
            "length": 144,
            "severity": "FATAL",
            "code": "3D000",
            "file": "/home/ec2-user/padb/src/pg/src/backend/utils/init/postinit.c",
            "line": "401",
            "routine": "InitPostgres"
        }
    }
}

2018-11-15T16:41:09.403Z	3d676db8-e8f5-11e8-a135-6b356668319a
{
    "redshift-cdr.cc5mfylzdhpr.us-east-1.redshift.amazonaws.com": {
        "status": -1,
        "error": {
            "name": "error",
            "length": 144,
            "severity": "FATAL",
            "code": "3D000",
            "file": "/home/ec2-user/padb/src/pg/src/backend/utils/init/postinit.c",
            "line": "401",
            "routine": "InitPostgres"
        }
    }
}

2018-11-15T16:41:09.441Z	3d676db8-e8f5-11e8-a135-6b356668319a
{
    "errorMessage": "error"
}

END RequestId: 3d676db8-e8f5-11e8-a135-6b356668319a
```

**Comment by IanMeyers** [comment]
If you edit the LambdaRedshiftBatchLoadConfig table for the s3 prefix being loaded, you'll see an entry loadClusters, which is an array of struct. It will look something like this:

```
"loadClusters": [
    {
      "clusterDB": "master",
      "clusterEndpoint": "my-cluster-endpoint",
      "clusterPort": 5439,
      "connectPassword": "XXX",
      "connectUser": "master",
      "targetTable": "ian_test",
      "truncateTarget": false,
      "useSSL": true
    }
  ]
```

set values `clusterDB` and `connectUser`. If you want to load into a schema that isn't public or the `connectUser`, then put the schema name in the `targetTable`.

**Comment by jagilbert27** [comment]
Success: I got my first batch loaded!

There are two fields in there that represent the table to be loaded: clusterDB and targetTable.  
And there are three pieces that need to be specified: database, schema, table.
I have found that this does **not** work:
    ~~clusterDB: myDB.mySchema~~
    ~~targetTable: myTable~~

This **does** work:
```
clusterDB: myDB
targetTable mySchema.myTable
```
Thanks Ian!

**Comment by IanMeyers** [comment]
Great stuff! Really glad to hear it.

**Comment by jagilbert27** [comment]
My next challenge:  
I have 27 different csv file feeds that need to use the RSDL to load into 27 different target tables. 
How can I configure that? 
The CSV files can be distinguished by Regex if necessary.

Cheers,
Jeff

**Comment by IanMeyers** [comment]
Today you will need to have 27 separate input prefixes, and 27 separate batch load configurations. All the tables are treated as independent from the perspective of the loader.

**Comment by jagilbert27** [comment]
Thanks again Ian, that worked.  

To configure the Redshift Loader to load into multiple input tables:
1. Create a record for each target table in the LambdaRedshiftBatchLoadConfig and changed the values of s3Prefix and loadClusters[0].targetTable as necessary.
2. Write the input files into the (pseduo) directory structure to match the s3Prefix above.

-Jeff
