### ISSUE TITLE
Difference with Postgres driver vs. Redshift driver

### ISSUE THREAD

**Issue by andrewrguy** [awslabs/aws-lambda-redshift-loader#19]
I'm getting errors when loading my csv files from s3 into redshift with respect to the timestamp through this lambda function. Here is the error from CloudWatch:
![screen shot 2015-04-21 at 2 54 29 pm](https://cloud.githubusercontent.com/assets/9866927/7260203/8c077380-e836-11e4-9284-3d9c97c4fae1.png)

And in the stl_load_errors table:
![screen shot 2015-04-21 at 2 54 45 pm](https://cloud.githubusercontent.com/assets/9866927/7260225/a3caa6d6-e836-11e4-9fc4-f6e682198046.png)

I can load these files without a problem running a simple COPY command from SqlWorkbench. The only difference I see is that this lambda function is using the Postgres driver (which Redshift no longer recommends) and my Workbench is connected with the Redshift driver. I don't really care, I just need my data loaded. Does Postgres not like the quotes around the date?

thanks,
Andy

**Comment by IanMeyers** [comment]
Hmm, I suppose that it could be the quotes. Can you try adding the value REMOVEQUOTES to the additional copy options. If that doesn't work, then also try adding TIMEFORMAT 'YYYY-MM-DD HH:MI:SS' or as outlined in the docs for the COPY command?

**Comment by andrewrguy** [comment]
Thanks Ian. Adding REMOVEQUOTES seemed to work. Yay!

**Comment by andrewrguy** [comment]
Had to reopen this as I found out REMOVEQUOTES does not play well with CSV. I'm guessing you are adding CSV as an option to COPY command based on the answer to one of the setup questions (CSV or JSON). So I added TIMEFORMAT 'auto' which got me past the date issue, but on to the next.... One of my columns contains a json string (which has commas in it). These commas are incorrectly being interpreted as column delimiters. The json string is quoted as such in the csv:

```
"{""client"":101,""subid"":""blahblah""}"
```

Again, the Redshift driver has no problem with this json string. So, back to the CSV option. What character are you specifying as the quote, if any?

Thanks.

**Comment by andrewrguy** [comment]
Update: I added COPY options as below:

```
timeformat as 'auto' csv quote as '"'
```

This did the trick. Again, it might be worth dropping in the new Redshift driver, so the experience is the same across tutorials, examples, etc in AWS documentation.

**Comment by IanMeyers** [comment]
Hi Andrew,

Glad to hear that you've got this resolved, but in fact this shouldn't be anything to do with which driver you use to connect to the cluster to run the COPY command. The command gets sent to the compute nodes, which then apply their internal logic to the data downloaded from S3, Dynamo DB, EMR or an SSH endpoint, and at no point in this flow is an ODBC or JDBC driver relevant. If you can email me outside of github on meyersi@amazon.com, I'd love to try and get to the root cause of the issue.

Thx,

Ian

**Comment by kessler** [comment]
Hi @andrewrguy 

Not sure if its entirely relevant but it might be...

I've had really good experience with applying Dollar-Quoted String Constants when inserting strings to redshift/pg database, you can read about it [here](http://www.postgresql.org/docs/8.3/interactive/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING)

And also see an implementation example [here](https://github.com/kessler/db-stuff/blob/master/lib/PostgresDatastore.js#L91-L106)

**Comment by andrewrguy** [comment]
Hi @kessler Thanks for the comment. I finally realized that putting 'CSV' as a copy option was the key to my issues. I assumed it was being put in because the setup script asks if the data is CSV or JSON, however the option is not in there if you answer CSV.

**Comment by IanMeyers** [comment]
The default format is CSV, indicated by setting a delimiter and not setting JSON. However, the CSV option also turns on extended CSV support such as "automatically escape delimiters, newline characters, and carriage returns". I think for now this needs to stay as an extra copy option, as customers may want to indicate the 'quote as' clause independently.
