### ISSUE TITLE
Node.js 6.10 End Of Life

### ISSUE THREAD

**Issue by jagilbert27** [awslabs/aws-lambda-redshift-loader#191]
With AWS announcing End Of Life for Node 6.10
Does the current branch still require Node 6.10?
Is anyone addressing this?

**Comment by chrisjameswilliams** [comment]
upvote for the above issue.

Invokes for functions configured to run on node.js 6.10 will continue to work normally, however the ability to create new Lambda functions configured to use the node.js 6.10 runtime will be disabled on April 30 2019. Code updates to existing functions using node.js 6.10 will be disabled 30 days later on May 30 2019

**Comment by IanMeyers** [comment]
I've pushed a documentation fix to address this point. The functionality was actually built on Node .10, and we have customers running it on a variety of engines. I have not tested it on Node versions higher than 6.10, but expect to continue to maintain the module, and so please report any issues on this topic and I will do my best to fix quickly.

**Comment by NickKellett** [comment]
I upgraded a dozen functions to 8.10 runtime and tested - everything seems fine (after 48 hours).

**Comment by george-viaud** [comment]
Currently yml specifies nodejs6.10 which is no longer supported during creation lambda function so cloudformation fails.  Going to try to switch it out for 8.10 and give it a go.
