### ISSUE TITLE
Erroneous string operation for filenames having multiple `+` and `%2B`

### ISSUE THREAD

**Issue by myonlinecode1988** [awslabs/aws-lambda-redshift-loader#193]
The `replace` function replaces `only the first instance` of `+` and `%2B` in a given string. So if a string has multiple `+` or `%2B`; only the first instance gets replaced which results in faulty manifest files. We need to change the logic from `replace` to `replace all`.

https://github.com/awslabs/aws-lambda-redshift-loader/blob/2f6ad93b2fda016254adb3e03e992549f055df5f/index.js#L789

```
Input:
var msg1='foo+bar+baz.avro'
var msg2='foo%2Bbar%2Bbaz.avro'


//Wrong
console.log(msg1.replace('+', ' ').replace('%2B', '+')) 

//Correct
console.log(msg1.replace(/\+/g, ' ').replace(/%2B/g, '+'))

//Wrong
console.log(msg2.replace('+', ' ').replace('%2B', '+')) 

//Correct
console.log(msg2.replace(/\+/g, ' ').replace(/%2B/g, '+'))

Output:
'foo bar+baz.avro'(wrong)
'foo bar baz.avro' (correct)
'foo+bar%2Bbaz.avro'(wrong)
'foo+bar+baz.avro'(correct)
```
Suggested Modification:
`url: 's3://' + batchEntries[i].replace(/\+/g, ' ').replace(/%2B/g, '+'),`

**Comment by IanMeyers** [comment]
Thanks for spotting - have fixed this in cb71e44.

**Comment by IanMeyers** [comment]
Patch goes into version 2.6.9 also - patched on website and S3.

**Comment by myonlinecode1988** [comment]
Thanks for the quick fix!
