### ISSUE TITLE
The loader does not response to wildcard paths

### ISSUE THREAD

**Issue by canyousayyes** [awslabs/aws-lambda-redshift-loader#20]
Hello,
With reference to #5,I have tried the loader v.1.1.2 for the wildcard paths function with the following settings:
`Enter the S3 Bucket & Prefix to watch for files > mybucket/click_events/y=*/m=*`

Then I have uploaded a file to the path `s3://mybucket/click_events/y=2015/m=04/16.json` using AWS nodejs SDK.
`aws s3 cp ~/local/16.json s3://mybucket/click_events/y=2015/m=04/16.json`

Unfortunately I have found this error message in the CloudWatch log:
`unable to load configuration for mybucket/click_events/y%3D2015/m%3D04`

Looks like it has encoding problem?

**Comment by IanMeyers** [comment]
Yes, it was indeed - fixed in AWSLambdaRedshiftLoader-1.1.5.zip
