### ISSUE TITLE
Configurations overlap

### ISSUE THREAD

**Issue by andrewrguy** [awslabs/aws-lambda-redshift-loader#22]
I wanted to upgrade this lambda function to the new 2.0 one. So I deleted the current function and re-uploaded the new zip file. When I went to add my event source I got this error message: "Configurations overlap. Configurations on the same bucket cannot share a common event type." I only have this one lambda function and nothing else is receiving event updates from that bucket.

**Comment by danmiley** [comment]
Take a look at the S3 dashboard for that bucket, there may be a residual event notification left over in the "Events" panel on the RHS of the dash.  Delete it if there is one, and you should be unblocked.

**Comment by ghost** [comment]
Go to your bucket in s3
inside it Propieties>Events
Select the event and click on delete
