### ISSUE TITLE
Flush Required

### ISSUE THREAD

**Issue by KyleGobel** [awslabs/aws-lambda-redshift-loader#23]
I started getting throttled on lambda so I changed some settings in my app.

Now I get this alert every time it runs

```
"Unable to write <filename>.json.gz in 100 attempts. Failing further processing to Batch <batchId> which may be stuck in 'locked' state. If so, unlock the back using `node unlockBatch.js <batch ID>`, delete the processed file marker with `node processedFiles.js -d <filename>`, and then re-store the file in S3"
```

When manually running the lambda I get the error message that flush is required.

I've tried walking through the code to see what it's looking for or what the problem is, and will continue to do so but I thought maybe someone else can give me a hand.

Ideally I would just like to know what I can change in dynamo to get this working again.  I tried changing the currentBatch entry in the dynamo, and also changed the states of some of the batches trying to get them to work. Nothing has worked.  Every new file gets the same alert (and I get a lot of them).

Any help would be amazing.  Thanks

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear that you are having this issue. Can you use the queryBatches.js script with the Batch ID that's on the configuration item for the bucket, and let me know what the status is? Also, please email me directly at meyersi@amazon.com and we can get to the root cause.

Thx,

Ian

**Comment by IanMeyers** [comment]
Also, could you possibly send me the full CloudWatch Log where you are seeing the above error?

Thx,

Ian

**Comment by tomekzbrozek** [comment]
hey @KyleGobel @IanMeyers did you get to any conclusion on this one? I'm just started seeing the same error on one of the 9 configuration items in DynamoDB (but just one!) -- all files corresponding to that item are failed to be loaded. When I query batch status with:
```
node describeBatch.js --s3-prefix ... --batch-id 397beb25-b868-43ec-a013-d60a683fb54f
```
I get such status info:
```
...
   "writeDates":{
      "NS":[
         "1632157356.768",
         "1632157414.684",
         "1632157384.191",
         "1632157351.526"
      ]
   },
   "status":{
      "S":"complete"
   },
   "lastUpdate":{
      "N":"1632157416.282"
   },
   "clusterLoadStatus":{
      "S":"{\"...cluster host...\":{\"status\":0,\"error\":null}}"
   },
   "batchId":{
      "S":"397beb25-b868-43ec-a013-d60a683fb54f"
   }
```

I would appreciate any thoughts on that, thanks!

**Comment by IanMeyers** [comment]
That looks like it loaded OK. Are you sure the files haven't been loaded? Do they appear in the Processed Files table?
