### ISSUE TITLE
No configuration found for <bucket-name>

### ISSUE THREAD

**Issue by pandeyp** [awslabs/aws-lambda-redshift-loader#24]
Hi,

I have followed the steps outlined in your README document. I did a git clone and added AWSLambdaRedshiftLoader-2.0.0.zip into my Lambda function. Then I added aws-sdk as a node module. I have my AWS credentials for accessing S3 bucket at ~/.aws/credentials file which I am assuming will be automatically picked up. Then I ran node setup whose script is given below. 

After running the setup script, whenvever I try uploading a test file to s3 I am getting the following log in Cloudwatch. From the code, I can tell configuration for load in Dynamo DB is not found whenever the lambda function is triggered. Please help.

Cloudwatch Log:

```
START RequestId: 48273add-18ac-11e5-91f3-4f69165d9383 
2015-06-22T06:59:58.284Z    48273add-18ac-11e5-91f3-4f69165d9383    No Configuration Found for test-bucket
END RequestId: 48273add-18ac-11e5-91f3-4f69165d9383 
REPORT RequestId: 48273add-18ac-11e5-91f3-4f69165d9383  Duration: 919.97 ms Billed Duration: 1000 ms Memory Size: 128 MB    Max Memory Used: 18 MB  

```

Setup Script:-

``````
Enter the Region for the Configuration > us-east-1
Enter the S3 Bucket & Prefix to watch for files > test-bucket
Enter a Filename Filter Regex > 
Enter the Cluster Endpoint > red****.*********.us-east-1.redshift.amazonaws.com
Enter the Cluster Port > 5439
Enter the Database Name > dev
Enter the Table to be Loaded > comma
Should the Table be Truncated before Load? (Y/N) > N
Enter the Database Username > ****
Enter the Database Password > ****
Error during Master Key creation
Error during resolution of Customer Master Key
Enter the Data Format (CSV or JSON) > CSV
Enter the CSV Delimiter > ,
Enter the S3 Bucket for Redshift COPY Manifests > testSymm
Enter the Prefix for Redshift COPY Manifests > /success/
Enter the Prefix to use for Failed Load Manifest Storage > /failure/
Enter the Access Key used by Redshift to get data from S3 > *******
Enter the Secret Key used by Redshift to get data from S3 > ********
Error during Master Key creation
Error during resolution of Customer Master Key
Enter the SNS Topic ARN for Successful Loads > 
Enter the SNS Topic ARN for Failed Loads > 
How many files should be buffered before loading? > 1
How old should we allow a Batch to be before loading (seconds)? > 1
Additional Copy Options to be added > 
Creating Tables in Dynamo DB if Required
{"TableName":"LambdaRedshiftBatchLoadConfig","Item":{"truncateTarget":{"BOOL":false},"currentBatch":{"S":"d17f10c7-a426-4e43-b8c5-c54a391cb6a6"},"version":{"S":"2.0.0"},"loadClusters":{"L":[{"M":{"clusterEndpoint":{"S":"redshift**8.redshift.amazonaws.com"},"clusterPort":{"N":"5439"},"clusterDB":{"S":"dev"},"targetTable":{"S":"comma"},"truncateTarget":{"BOOL":false},"connectUser":{"S":"test"},"connectPassword":{}}}]},"s3Prefix":{"S":"dataexplorer-secure"},"dataFormat":{"S":"CSV"},"csvDelimiter":{"S":","},"manifestBucket":{"S":"testSymm"},"manifestKey":{"S":"/success/"},"failedManifestKey":{"S":"/failure/"},"accessKeyForS3":{"S":"****"},"secretKeyForS3":{},"batchSize":{"N":"2"},"batchTimeoutSecs":{"N":"3"}}}
{"message":"Supplied AttributeValue is empty, must contain exactly one of the supported datatypes","code":"ValidationException","time":"2015-06-16T11:31:58.388Z","statusCode":400,"retryable":false,"retryDelay":0}```

``````

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear you are having this issue. The problem is that when you tried to create the configuration, it was supplied with a NULL password. This either means that you didn't enter a password, or that the call to KMS failed and we didn't catch that condition. Did you enter a password on setup?

Thx,

Ian

**Comment by pandeyp** [comment]
Hi,

Thanks for you quick reply. I am using the default database provided in redshift called 'dev' and I have supplied both the username and password created during the time of Redshift cluster creation. I have also tried creating a user on default database (dev) and granting him/her insert previledge as outlined in the document but to no avail.

Hope to hear from you soon.

**Comment by IanMeyers** [comment]
OK - am going to push a change which creates fatal errors when the encryption cannot happen, but unfortunately in either case I can't reproduce what you are seeing. Can you confirm the following installation process:

```
Unzip AWSLambdaRedshiftLoader-2.0.0.zip
cd AWSLambdaRedshiftLoader
npm install
node setup.js
```

Can you also please confirm that the IAM Profile that you are using to run the setup has Write Privileges to DDB as well as:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1434969436000",
            "Effect": "Allow",
            "Action": [
                "kms:DescribeKey",
                "kms:List*",
                "kms:Encrypt"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

Also please feel free to email me on meyersi@amazon.com to work on this with a bit more detail. Also please note that while you blanked the Redshift cluster details in your post, you didn't do so in the error trace.

Thanks,

Ian

**Comment by pandeyp** [comment]
Hi,

Thanks for the reminder. Redshift cluster details are now blanked in the error trace. 

I am uploading a test CSV to S3 from my local machine and also running setup.js from my local machine. In my local machine the only credentials I have for access to s3 are aws-access-key and aws-secret-key. I am not sure if  IAM Profile is relevant in my case while I upload to s3 and run the setup from my local machine. 

I will however add write privileges to Dynamo DB to my IAM profile and lambda_exec_role that I am using to login to the AWS console, create lambda function and upload files to S3. I will follow up the steps you have outlined above and get back to you shortly.

**Comment by pandeyp** [comment]
Issue resolved. Authorities for kms:createKey and kms:createAlias were missing from my IAM profile. After adding these authorities, the zip file worked flawlessly.

**Comment by tomdeblende** [comment]
I have the same issue. 

No Configuration Found for cloudar/

I checked for the existence of the authorities mentioned above: no luck. Anything I can try to debug?
