### ISSUE TITLE
Flushing Partial Batches not working for multiple tables/config scenario

### ISSUE THREAD

**Issue by FrancisCSLau** [awslabs/aws-lambda-redshift-loader#26]
We have 5 rows in the LambdaRedshiftBatchLoadConfig table that writes to 5 different target tables. When we use the dummy file approach to flush the partial batches, only 1 open batch gets flushed. We are running the generate-trigger-file.py 5 times and we do see a dummy file in each of the 5 S3 locations.   We are not sure why the flush is not working. We have tested this several times and each time, it only flush 1 batch and not the other 4. Thanks for help.

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear that you are having this issue. Can you try to paste some of the CloudWatch Logs for an invocation of the function based on the dummy file?

Thx,

Ian

**Comment by FrancisCSLau** [comment]
We will capture that and email to you after our current test run. Probably
in 90 minutes.

Francis

**Comment by FrancisCSLau** [comment]
Ian, we tried to repro this again but it seem to be flushing all tables now. We will close this issue for now and if we can repro it, we will reopen the issue. Thanks!

**Comment by blanders-zz** [comment]
So, what we are seeing is open batches, then we add a dummy file via the provided tool, then no reaction in Redshift (no loading of data), even though Cloudwatch indicates that it sees the dummy file.

![screen shot 2015-07-24 at 2 50 05 pm](https://cloud.githubusercontent.com/assets/731970/8885417/32365f6a-3214-11e5-9351-8c033aa0c85f.png)
![screen shot 2015-07-24 at 2 56 09 pm](https://cloud.githubusercontent.com/assets/731970/8885419/37681d84-3214-11e5-9c77-f3a48f5b77c8.png)

**Comment by FrancisCSLau** [comment]
Ian, we can repro this now. We are reopening this issue and Bill has posted the details above.

**Comment by IanMeyers** [comment]
Just coming back to this - sorry for the delay. Can you post the full configuration for 'files-for-rs2/user-product'? Alternatively you can email to meyersi@amazon.com and I'll have a look.

**Comment by IanMeyers** [comment]
Closed as I've not received the full configuration, so assume this is no longer an issue.
