### ISSUE TITLE
Preparing your Amazon Redshift Cluster

### ISSUE THREAD

**Issue by jstoor** [awslabs/aws-lambda-redshift-loader#30]
In the readme it states:

_In order to load a cluster, we’ll have to enable AWS Lambda to connect. To do this, we must enable the cluster security group to allow access from the public internet. In the future, AWS Lambda will support presenting the service as though it was inside your own VPC._

Due to our security policy, we're unable to grant public access.

Will this prevent the sample loader from loading the example csv files into redshift ?

Is there a workaround ?

Thank You

**Comment by IanMeyers** [comment]
Unfortunately yes, today Lambda is only accessible via AWS Public Endpoints. You can find the list of endpoints here http://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html. So in order for the Lambda Loader to connect to Redshift, you'll need to open your Cluster Security Group to the CIDR blocks indicated in the ip_ranges.json file.

**Comment by pandeyp** [comment]
Hi Ian,

Running into the same problem here. I am getting timed out after 60 seconds due the loader not being able to connect to our Redshift cluster in our VPC and is not publicly accessible. The ip_ranges.json file is a bit confusing as to what ranges to open our secuirty groups to for this to work. Is there a timeline for making AWS Lambda available inside a VPC?

**Comment by IanMeyers** [comment]
Hello,

I have shared your feedback with the Lambda team, but unfortunately I don't have any information to share about this requirement. As a way to ensure you are up to date with AWS new features, you can subscribe to the What's New RSS Feed at http://aws.amazon.com/new/feed

Sorry I can't be of more assistance.

Ian
