### ISSUE TITLE
Diagnosing errors

### ISSUE THREAD

**Issue by andrewrguy** [awslabs/aws-lambda-redshift-loader#31]
Can you give a basic checklist on how to troubleshoot when a batch does not load? For example, under what circumstances would a batch get locked? I have batches that error out, but the message is often cryptic, like: 

```
"errorMessage": {
    "S": "{\"ttg-blah.blah.us-east-1.redshift.amazonaws.com\":{\"status\":-1,\"error\":{\"name\":\"error\",\"length\":179,\"severity\":\"ERROR\",\"code\":\"25P02\",\"file\":\"\/home\/awsrsqa\/padb\/src\/pg\/src\/backend\/tcop\/postgres.c\",\"line\":\"1809\",\"routine\":\"execOneParseTree\"}}}"
  },
```

I look in stl_load_errors, but there is nothing related to that batch in there. Is there another place to look?

**Comment by andrewrguy** [comment]
Here's one that I don't know how to fix: "The level of configured provisioned throughput for the table was exceeded." I'm guessing this is for the DynamoDB tables, but which table and is it read or write?

![screen shot 2015-07-17 at 12 48 51 pm](https://cloud.githubusercontent.com/assets/9866927/8752502/6bbb91fc-2c82-11e5-8028-805d80df3c73.png)

**Comment by andrewrguy** [comment]
Don't know if this is related, but it is also coming up a bunch:

![screen shot 2015-07-17 at 12 40 15 pm](https://cloud.githubusercontent.com/assets/9866927/8752520/8609257e-2c82-11e5-9b83-6b115591ea57.png)

**Comment by IanMeyers** [comment]
Hey Andrew - sorry for the delay. I hope to be able to look at this early next week. Is it all batches, or only a few?

**Comment by IanMeyers** [comment]
On the provisioned iops, it could be reads or writes tbh. I would suggest keeping them in sync and setting them to the overall file receipt rate plus maybe 10%.

**Comment by andrewrguy** [comment]
All batches are getting the "Cannot read property 'Item' of null" error.
The provisioning problem is popping up less often.

**Comment by andrewrguy** [comment]
Looking at the Monitoring tab in Dynamo I see the provisioning error is related to reading the LambdaRedshiftBatchLoadConfig table, so I'm adjusting that now, should clear up that problem.

**Comment by andrewrguy** [comment]
I am no longer seeing "Cannot read property 'Item' of null" errors, However I am seeing "Reload of Configuration Complete after attempting Locked Batch Write". Is that an issue to worry about?

![screen shot 2015-07-21 at 4 30 17 pm](https://cloud.githubusercontent.com/assets/9866927/8811758/10fb5008-2fc6-11e5-95cc-cd35dbcab90c.png)

**Comment by IanMeyers** [comment]
If it's happening all the time then the open batch is stuck and you should set a new batch and reprocess. However if it only happens sometimes, then this means you have the batch size set too small.

**Comment by andrewrguy** [comment]
It's intermittent, so I'll adjust batch size

**Comment by andrewrguy** [comment]
Okay, contrary to my other comment, this is happening all the time for one of my configurations. How do I find the open batch and reprocess? If I query for 'locked' sometimes I get no results and sometimes there is just one result. Is it trashing between locked and open?

**Comment by andrewrguy** [comment]
Okay, contrary to my last comment, this is happening all the time for one of my configurations. Now there is an error about failing after 100 attempts. However, the batch does not end up in the locked state, because I can't find it with queryBatches. How do I set a new batch and reprocess?

**Comment by IanMeyers** [comment]
So in that case, the process that would have completed the load has errored in some way, and so you should just use the unlockBatch.js script to unlock it for that prefix, and then the next file to be added to the batch will cause it to be processed.

**Comment by andrewrguy** [comment]
Great, I believe that cleared it up.

**Comment by endario** [comment]
I've also witnessed the same problems.

It would be great to log which table was causing the 'insufficient throughput' problems, as now we have to guess. The CloudWatch diagram is the only metric I can get my hands on, which obviously only reports 5 minute averages and not per second spikes.

---

For 'Reload of Configuration Complete after attempting Locked Batch Write', does the program eventually give up and put the batch in locked / error state?

Thanks.

**Comment by IanMeyers** [comment]
Good suggestion and easy to implement. Will do that in next version.

**Comment by IanMeyers** [comment]
And yes, after 100 attempts to add the file to the open batch, the operation will be terminated. All other operations have a default retry of 10 attempts.

**Comment by IanMeyers** [comment]
Tables which are receiving ProvisionedThroughputExceededException now log when this error is raised.
