### ISSUE TITLE
Add Support for Specifying Column Names to support Defaulted Columns

### ISSUE THREAD

**Issue by FrancisCSLau** [awslabs/aws-lambda-redshift-loader#32]
We want a column in a table in Redshift that defaults to GetDate() so that we know when the row is copied into Redshift. But we cannot get it work work with code changes to the Loader

Here is the walk-thru. 

**Table Definition:**
Field is shown below "dbImportDateTime"

CREATE TABLE userData (
  userID bigint,
  userInsertDateTime timestamp ,
  firstName varchar(200) ,
  domain varchar(400) ,
  languageFriendly varchar(200) ,
  countryFriendly varchar(200) ,
  SharedUser smallint,
  SignupBucket varchar(200) ,
  SignupSource varchar(400) ,
  SignupSubSource varchar(400) ,
  SignupCampaign varchar(200) ,
  SignupSegment varchar(200) ,
  selectedRole varchar(400),
  dbImportDateTime timestamp DEFAULT GETDATE(),
  PRIMARY KEY (userID) 
  )
  DISTKEY(userID)
  COMPOUND SORTKEY(userID);  

**Copy Command Generated by Redshift Loader Lambda function**

COPY userData 
        from 's3://redshift-copy-manifests/user-data/manifest-2015-07-15-20:06:10-7234' 
        with credentials as SNIP
    manifest 
    json 's3://json-paths/user-data.txt';

**Error from Copy Command**

An error occurred when executing the SQL command:
[Amazon](500310) Invalid operation: Number of jsonpaths and the number of columns should match. JSONPath size: 13, Number of columns in table or column list: 14;

**JSON Path File**
{ 
    "jsonpaths": [
         "$.userID",
         "$.userInsertDateTime",
         "$.firstName",
         "$.domain",
         "$.languageFriendly",
         "$.countryFriendly",
         "$.SharedUser",
         "$.SignupBucket",
         "$.SignupSource",
         "$.SignupSubSource",
         "$.SignupCampaign",
         "$.SignupSegment",
         "$.selectedRole"
    ]
}

**Summary of Error**
The error message is accurate. JSON Path have 13 fields and Table has 14 fields but I was hoping that the 14th field will be filled in with the Default of GetDate()

**Solution**
We found that by adding the column names, the copy works and the last column is defaulted to the load date.  Copy command shown below.

COPY userData (
    userID,
    userInsertDateTime,
    firstName,
    domain,
    languageFriendly,
    countryFriendly,
    SharedUser,
    SignupBucket,
    SignupSource,
    SignupSubSource,
    SignupCampaign,
    SignupSegment,
    selectedRole
        )
        from 's3://redshift-copy-manifests/user-data/manifest-2015-07-15-20:06:10-7234' 
        with credentials as SNIP
    manifest 
    json 's3://json-paths/user-data.txt';

**Code Changes Needed**
We will need to make some code changes to the Lambda Loader but I thought I check with you before making such a change to make sure we are going down the right path and that you will merge our code change back into your codebase. 
1. Add support for a new column in the LambdaRedshiftBatchLoadConfig table to support specifying comma delimited column names. If null, copy command will not include the column names. If specified, column names are added to copy command
2. Update setup.js to support this new column
3. Update index.js to include column names in copy command if provided in config table

Is this the right approach? Any other things we should watch out for?

**Comment by IanMeyers** [comment]
Hello,

Sounds like a really good feature addition. I think your synopsis of the changes are correct.

Regards,

Ian

**Comment by IanMeyers** [comment]
Hello,

Sounds like a really good feature addition. I think your synopsis of the changes are correct.

Regards,

Ian

**Comment by jjmartin** [comment]
has any progress on this been made? i'd be interested in taking advantage of the feature of being able to specify column names - ideally, i'd like to pre-read the csv file header and determine them from that...

**Comment by FrancisCSLau** [comment]
The enhancements pull request have been sent to Ian and I think he has accepted it. However, I am not sure if he has built it into the dist packages. We have been using it for a few weeks now so it is working well for us. Our use case is slightly different though. It is to support default values provided by Redshift and we are using JSON data files with JSON paths specified.

**Comment by IanMeyers** [comment]
Hello,

Yes, the changes are now available in the setup and index.js. I'm working on an enhancement to log when ProvisionedThroughputExceeded exceptions happen on tables, and then will ship a fully built 2.0.6 zip. Furthermore, I'm changing the packaging model, so that only upgrades, index and kmsCrypto are built into the Lambda deployment zip. This will minimise the size of the function, but will require that customers use the base javascript files for setup and maintenance activities.

Regards,

Ian

p.s.

Using the file header to resolve columns would be quite neat, but given the processing model today I don't think it will be possible.

**Comment by IanMeyers** [comment]
Pushed 2.0.6
