### ISSUE TITLE
CopyCommand Bug

### ISSUE THREAD

**Issue by endario** [awslabs/aws-lambda-redshift-loader#33]
Hey guys, much appreciated for writing this beautiful tool which is no doubt going to help with our Redshift loading.

I noticed a minor bug in line 748 of index.js, instead of

``` javascript
copyOptions = copyCommand + '  ' + config.dataFormat.S + '  \'auto\'  \n';
```

it should be

``` javascript
copyOptions = copyOptions + '  \'auto\'  \n';
```

as now the whole copyCommand is repeated if `JSON auto` is used.

Also could you please add a space before `with` in line 842.

Thanks and all the best!

Ren

**Comment by IanMeyers** [comment]
Thanks for the heads up. Both have been fixed in 2.0.5

**Comment by endario** [comment]
Prompt fix, thanks!

Note that this is not yet fully resolved. `+ config.dataFormat.S` is still being duplicated in line 748. (You already appended it once a few lines before outside the if block).

**Comment by IanMeyers** [comment]
Not sure I understand. Line 798 is part of building the database connection string. What's the issue that you are seeing be generated?

**Comment by endario** [comment]
My apologies! My eyes were playing tricks on me. :)

It should be line 748 instead:
`copyOptions = copyOptions + ' ' + config.dataFormat.S + ' \'auto\' \n';`
which is duplicating `+ config.dataFormat.S` that was already appended by
`copyOptions = copyOptions + ' ' + config.dataFormat.S;`
in line 743.

So you get JSON JSON 'auto' instead of JSON 'auto'

**Comment by IanMeyers** [comment]
Doh. Fixed now. Missed that - can you please verify?

**Comment by endario** [comment]
Thanks. :)
