### ISSUE TITLE
Support for IGNOREHEADER in copy command

### ISSUE THREAD

**Issue by jjmartin** [awslabs/aws-lambda-redshift-loader#37]
This should be an easy add - i'll try to get it in tomorrow...  - Our CSV have a header row, so our copy command needs IGNOREHEADER 1 as part of the options

**Comment by IanMeyers** [comment]
Because of the large number of possible copy options, I don't think it's sustainable to code for every one. Instead there's the general COPY OPTIONS entry that you should be able to put this option into. Does that work for you?

**Comment by jjmartin** [comment]
i'll check that out this morning and let you know

**Comment by jjmartin** [comment]
that works - i hadn't updated my config so that value was missing.
