### ISSUE TITLE
When trying to run configureSample.sh getting error with Customer Master key

### ISSUE THREAD

**Issue by celik0311** [awslabs/aws-lambda-redshift-loader#4]
Below error when trying to execute the sample 

```
CREATE USER
create table lambda_redshift_sample(
column_a int,
column_b int,
column_c int
);
CREATE TABLE
Unknown Error during Customer Master Key describe
Error during resolution of Customer Master Key
Enter the Region for the Redshift Load Configuration >
```

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear that you are having this problem. Can you check if the credentials you are using for the local JavaScript sdk give you rights to the aws key management service?

Thx,

Ian

**Comment by celik0311** [comment]
I believe that they do not sure if this helps:

```
{ [ValidationException: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes]
  message: 'Supplied AttributeValue is empty, must contain exactly one of the supported datatypes',
  code: 'ValidationException',
  time: Wed Mar 11 2015 17:26:05 GMT-0400 (EDT),
  statusCode: 400,
  retryable: false,
  retryDelay: 0 }

```

**Comment by celik0311** [comment]
Proper access rights confirmed

**Comment by IanMeyers** [comment]
The ValidationException you provided would be raised by DynamoDB if one of the configuration values was missing. Did you enter all of the requested values for the sample setup?

Thx,

Ian

**Comment by celik0311** [comment]
Not sure if this helps

```
Creating Tables in Dynamo DB if Required
{"TableName":"LambdaRedshiftBatchLoadConfig","Item":{"truncateTarget":{"BOOL":false},"currentBatch":{"S":"a43dc4f3-6b8d-4f1d-8377-0f368cd6cc41"},"targetTable":{"S":"lambda_redshift_sample"},"dataFormat":{"S":"CSV"},"csvDelimiter":{"S":"|"},"manifestKey":{"S":"lambda-redshift/load-manifest"},"failedManifestKey":{"S":"lambda-redshift/failed-manifest"},"batchSize":{"N":"2"},"batchTimeoutSecs":{"N":"60"},"connectUser":{"S":"test_lambda_load_user"},"connectPassword":{},"s3Prefix":{"S":"celik-sample/input"},"manifestBucket":{"S":"celik-sample"},"clusterEndpoint":{"S":"examplecluster.amazonaws.com"},"clusterPort":{"N":"5XXX"},"clusterDB":{"S":"dev"},"accessKeyForS3":{"S":"BLAH-BLAH"},"secretKeyForS3":{}}}
{ [ValidationException: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes]
  message: 'Supplied AttributeValue is empty, must contain exactly one of the supported datatypes',
  code: 'ValidationException',
  time: Wed Mar 11 2015 17:57:27 GMT-0400 (EDT),
  statusCode: 400,
  retryable: false,
  retryDelay: 0 }
```

**Comment by IanMeyers** [comment]
Thanks very much for that. I see the issue now, which is an omission in the instructions to run the sample, which I will address as soon as possible. The issue is that the setup script is unable to communicate with the Key Management Service as the region has not been indicated. The region is derived from an environment variable AWS_REGION. To fix this, please run:

`export AWS_REGION=us-east-1` for US East, or use region 'eu-west-1' for Dublin

This should then write your sample configuration without further issues.

Thx,

Ian

**Comment by IanMeyers** [comment]
I've also fixed the setting of the region automatically in the `configureSample.sh`, which now requires the AWS Region to be used as an argument, and which exports the correct environment variable. If you sync GitHub and re-run `./configureSample.sh`, it should work OK. Do let us know if not.

Thanks and sorry for the trouble.

Ian

**Comment by celik0311** [comment]
Just tested and everything worked as expected. Thank you for your help and the timely responses!
