### ISSUE TITLE
powershell build -deploy loses triggers

### ISSUE THREAD

**Issue by jjmartin** [awslabs/aws-lambda-redshift-loader#40]
i know i just added that file but i am running into an issue where the way i was uploading is losing the triggers i had set up on my lambda function.

Trying to figure out the Update Function powershell
https://forums.aws.amazon.com/thread.jspa?threadID=214760

but having a couple of issues,   I'll submit a pull request when i get this fixed.

**Comment by IanMeyers** [comment]
I believe this is now resolved, correct?

**Comment by jjmartin** [comment]
yea... thanks
