### ISSUE TITLE
support for multiple config's

### ISSUE THREAD

**Issue by jjmartin** [awslabs/aws-lambda-redshift-loader#41]
how would I add a 2nd config and either set triggers or a whole additional lambda to use the 2nd config?

**Comment by IanMeyers** [comment]
Configurations are keyed on S3 bucket and Prefix. If you wanted to test with two different configurations, then change the exiting configuration prefix to be 'new-'<existing prefix> and then create a new configuration with the <existing prefix>. You can then flip between these by updating the prefix value.
