### ISSUE TITLE
SetTimeout issue in index.js

### ISSUE THREAD

**Issue by nwayve** [awslabs/aws-lambda-redshift-loader#43]
Line 1170: `setTimeout(callback(), timeout);`

Should just be `setTimeout(callback, timeout);`  
Unless the anticipated result of the callback is a function.  
Saw this while a coworker was working with this library so I'm not 100% on the context of the code.

**Comment by IanMeyers** [comment]
Ah thanks - hadnt noticed that. Fixed in an update to 2.0.7
