### ISSUE TITLE
3 hour running query, redshift statement timeout needed

### ISSUE THREAD

**Issue by dbers** [awslabs/aws-lambda-redshift-loader#45]
Over the weekend we had our redshift locked with this query running for 3 hours:

COPY pending_updates_devices from
    's3://*****_-lambda-logs/**_***-updated-Success/manifest-2015-08-29-09:45:21-5214&#39; with credentials as '' manifest JSON 'auto' ;

I'm thinking the lambda function timed out but that query kept on executing.  When we noticed it we killed it and then everything started to behave like normal.

I'm wondering if there is a way to adding a statement timeout to the loader script.  something like this:

set statement_timeout to 60000;

I could edit the code and do this myself but wondering if there is something in place that can take care of this already.

Thanks 
Daniel

**Comment by IanMeyers** [comment]
Good suggestion - will add this in a subsequent release. Will leave open until it's released.

**Comment by IanMeyers** [comment]
Fixed in 2.0.8

**Comment by dbers** [comment]
Thanks

**Comment by aseem-poloniex** [comment]
```
set statement_timeout = 2;
set statement_timeout to 2;
```
Both these formats dont seem to work. 
I am able to run any time consuming sql without error after setting `statement_timeout`.

**Comment by IanMeyers** [comment]
Can you definitely see that the statement timeout is being applied in the debug log? The syntax using `=` is correct, so my guess it that it's not being correctly set.
