### ISSUE TITLE
More flexible configuration key

### ISSUE THREAD

**Issue by wrgoldstein** [awslabs/aws-lambda-redshift-loader#46]
I have a lambda function with event source bucket `foo` and prefix `bar/`, but the files I'd like to load into redshift (created by a third party) are created with a path like `foo/bar/baz/qux/norf/file123.gz`.  The `/qux/norf/..` part of the path changes over time as new directories are created.  

I would like the lambda function to always find a single dynamoDB configuration with key `foo/bar`.  I've forked this repo and changed the `searchKey` in `index.js` directly, but I would love to contribute back a more flexible solution.  Can you comment on whether that would make sense?  Maybe the lambda function can set the `searchKey` according to the lambda function's event source?

**Comment by IanMeyers** [comment]
So I think having an option which was built into the codebase that would SCAN the configuration and do regular expression matches against the config key would be the only way to deal with this. It would increase the cost of the initial event processing by the number of configuration items needed to process to get a match, but this would potentially be acceptable for low velocity loads. In essence, this would be a branch of the dynamoDB.getItem() request to instead do a SCAN based on a hard coded configuration option (similar to the debug flag).

**Comment by malaqueueit** [comment]
+1 I am trying to make this work with ELB logs that creates dynamic paths [year]/[month]/[day] and some other thrid party services that does the same. Any idea if this will go into the project?

**Comment by IanMeyers** [comment]
Hi Martin,

Thanks for the feedback. I'll look into a way of supporting more dynamic config paths. 

If your prefix in s3 is flexible, then we already support a certain amount of dynamic lookup by using an 'x=y' syntax in the prefix. For example rather than today being .../2016/01/05/... you could use .../yyyy=2016/mm=01/dd=05/... in the files being written. Then create the configuration entry of .../yyyy=_/mm=_/dd=*/... The loader will replace all the 'y' part of 'x=y' with stars before looking up the configuration. 

Thx,

Ian

**Comment by malaqueueit** [comment]
Hi Ian

Thanks for the quick reply. Unfortunately I don't control the path. This is decided by the ELB team (or any of the third party tools we use). So my path is something like:

mybucket/myprefix/AWSLogs/654864684/elasticloadbalancing/eu-west-1/2016/01/05/key.log

So what I really want to do is to match on mybucket/myprefix/AWSLogs/654864684/elasticloadbalancing/eu-west-1 as I want any file that has that prefix + whatever comes after. As I understand the problem, you currently do a GetItem to locate the matching item. What if you instead did a BatchGetItem to get the items:

mybucket
mybucket/myprefix
mybucket/myprefix/AWSLogs
mybucket/myprefix/AWSLogs/654864684
mybucket/myprefix/AWSLogs/654864684/elasticloadbalancing
mybucket/myprefix/AWSLogs/654864684/elasticloadbalancing/eu-west-1
mybucket/myprefix/AWSLogs/654864684/elasticloadbalancing/eu-west-1/2016
mybucket/myprefix/AWSLogs/654864684/elasticloadbalancing/eu-west-1/2016/01
mybucket/myprefix/AWSLogs/654864684/elasticloadbalancing/eu-west-1/2016/01/05

and then use the most specific match? There will be some backwards compatibility issues, but that could be solved by having a flag on the config entry which decides if partial prefix matches are allowed.

**Comment by malaqueueit** [comment]
Btw, we are interested in finding a solution for this problem, so we can do the implementation in a fork if we agree on solution and we will send a pull request. But we are also interested in having the solution as a part of the awslabs repository so we will not have to maintain our own fork.

**Comment by IanMeyers** [comment]
Certainly understand. If you shoot me a mail at meyersi@amazon.com I should be able to share a version you can test today.

**Comment by malaqueueit** [comment]
I sent you an email. My address should also be available on my profile. Thanks.

**Comment by IanMeyers** [comment]
malaqueueit now beta testing version 2.2.0 with support for dynamic prefix matching

**Comment by IanMeyers** [comment]
I've pushed 2.2.0 to Github for others to get started with. I will leave this issue open for a while so anyone can raise issues if needed.

**Comment by IanMeyers** [comment]
Closing as I think this is covered functionally. Please reopen if you have any issues with 2.2.0.
