### ISSUE TITLE
Hard coded 'csv' copy option causing failed loads

### ISSUE THREAD

**Issue by endario** [awslabs/aws-lambda-redshift-loader#51]
The hard coded 'csv' copy option (line 765) that is added in 2.0.7 seems to be breaking our previously functional upload process.

```
// add data formatting directives to copy options
if (config.dataFormat.S === 'CSV') {
    copyOptions = copyOptions + ' csv delimiter \'' + config.csvDelimiter.S + '\'\n';
}
```

We are using gzipped csv files and we have been using a selection of copy options such as REMOVEQUOTES and ESCAPE, that obviously have been working pre-2.0.7.

Now with the hardcoded **csv** option, Redshift is complaining with errors such as:
`CSV is not compatible with ESCAPE`
, etc.

I wonder if we have been using it wrong previously, or this change has not been properly verified?

**Comment by IanMeyers** [comment]
The FORMAT CSV option will automatically work with default quotes, so you don't need to add the REMOVEQUOTES option. Did you have a requirement for ESCAPE?

**Comment by pickhardt** [comment]
Yes - if you have a CSV with special characters in it. Otherwise you get an error like

`Missing newline: Unexpected character 0x74 found at location 51`

Any idea on what to do there?

**Comment by IanMeyers** [comment]
Understood. Given the way that the COPY command is constructed, we will have to add a setup option for escaped characters. I will be able to look at this in second week of October, but happy to take a pull request before then.

**Comment by pickhardt** [comment]
What will the setup option for escaped characters do? I have tried using a COPY with the ESCAPE option but get an error `CSV is not compatible with ESCAPE` so you can't just throw that option in there.

**Comment by IanMeyers** [comment]
Correct. If escape sequence is used then it will need to remove the 'format csv' and just set 'delimiter x' with the escape sequence.

**Comment by pickhardt** [comment]
So if I switch to no longer use the CSV option, and use DELIMITER ',' instead, are there other side effects of that? For instance, is it slower (is CSV loading optimized)?

**Comment by IanMeyers** [comment]
No difference in performance. 'Format csv' automatically escapes quotes and defaults the delimiter, that's all. You may also need to add the REMOVEQUOTES option.

**Comment by IanMeyers** [comment]
I've just pushed version 2.0.10 which adds a feature which should fix your issue. You should now be able to add copyOptions which include REMOVEQUOTES or ESCAPE and have the FORMAT CSV part of CSV loads be suppressed.
