### ISSUE TITLE
Is it possible to include source file(s) names in redshift tables while issuing copy statment?

### ISSUE THREAD

**Issue by ppandey224** [awslabs/aws-lambda-redshift-loader#53]
Does AWS lambda redshfit loader support inclusion of source file names in an additional column while copy from s3? 

A possible scenario could be:-

When I put 3 files  a.txt, b.txt and c.txt in s3 location : s3://test-bucket/test/ and this location is configured to automatically populate redshift table 'testfilenames' then the resulting table would be populated in the following manner:-

| field1 | field2 | field3 | filename |
| :-- | :-- | :-- | :-- |
| xty1 | abc | dey | a.txt |
| lala | xana | dula | a.txt |
| falal | katal | natal | b.txt |
| rara | fewa | begnas | b.txt |
| tata | mama | gaga | c.txt |

Please note that an extra column is added to table 'testlocation' with that dentoes the file's s3 location from which each record originates.

Thanks,

**Comment by IanMeyers** [comment]
Unfortunately the COPY command does not yet support this functionality, but I will forward the request to the relevant teams for consideration. Thanks for the feedback.

**Comment by ppandey224** [comment]
Ok. Thanks Ian.
