### ISSUE TITLE
Support DynamoDB streams?

### ISSUE THREAD

**Issue by juokaz** [awslabs/aws-lambda-redshift-loader#56]
Feature request.

Any plans to expand this to support [DynamoDB streams](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html) as a data source? This project sounds like it has the right framework to go beyond S3 and also handle dynamodb data.

**Comment by IanMeyers** [comment]
Hi,

Today you should probably use Amazon Kinesis Firehose to accomplish this task. Please see https://github.com/awslabs/lambda-streams-to-firehose for more information on how to forward Dynamo DB Update Streams to Amazon Kinesis Firehose using AWS Lambda.

Thx,

Ian
