### ISSUE TITLE
Unable to leverage "role" for S3 bucket access

### ISSUE THREAD

**Issue by ruthea** [awslabs/aws-lambda-redshift-loader#58]
In the setup.js it prompts for the access/secret key to access the S3 buckets to load data.  It mentions "If NULL then Lambda execution role credentials will be used", but if you leave NULL it errors out and says "You Must Provide an Access Key"

**Comment by IanMeyers** [comment]
Yep - dunno why that was inconsistent with my local code. This is now fixed. Sorry bout that!
