### ISSUE TITLE
The loader does not response to ObjectCreated:CompleteMultipartUpload

### ISSUE THREAD

**Issue by canyousayyes** [awslabs/aws-lambda-redshift-loader#6]
When we upload a huge file to S3 in aws javascript sdk, e.g.
`aws s3 cp 20mb_file s3://mybucket/metrics`

The event name is `ObjectCreated:CompleteMultipartUpload` instead of `ObjectCreated:Put`.

Therefore the Lambda function will generate the error `Invalid Event Name ObjectCreated:CompleteMultipartUpload` and halt.

How can this problem be fixed? Can the load support multipart upload?

**Comment by IanMeyers** [comment]
Hi Gene - thanks for bringing this to our attention - this was an obvious omission in our event filters. The Multipart Copy Event has now been added in version 1.1.1 of the deployable zip. You will have to redeploy the Lambda function, but your multi-part upload should now work fine.

**Comment by canyousayyes** [comment]
Hello IanMeyers, 
Thanks for the update on the tool, the function is now working =)

**Comment by IanMeyers** [comment]
Great!
