### ISSUE TITLE
No configuration found for <bucket-name>

### ISSUE THREAD

**Issue by tomdeblende** [awslabs/aws-lambda-redshift-loader#60]
I have the same issue as issue #24 . I tried the fix described in that topic, to no avail.

Event Data
START RequestId: 2c09fcea-b898-11e5-979e-c78c987ef064 Version: $LATEST 
2016-01-11T19:19:03.336Z    2c09fcea-b898-11e5-979e-c78c987ef064    No Configuration Found for cloudar/ 
END RequestId: 2c09fcea-b898-11e5-979e-c78c987ef064 
REPORT RequestId: 2c09fcea-b898-11e5-979e-c78c987ef064  Duration: 1026.64 ms    Billed Duration: 1100 ms Memory Size: 128 MB    Max Memory Used: 17 MB   

I used the sample script in the sample directory. What steps can I take to further troubleshoot this?

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear you have an issue! What version have you deployed, and what is the bucket and prefix for the events you've set up?

Thx,

Ian

**Comment by tomdeblende** [comment]
Hi Ian,

Thanks for your prompt reply. I have tried this with both 2.1.0 and 2.2.0. The bucket is cloudar.s3-website-eu-west-1.amazonaws.com with no prefix.

Thx,
Tom

**Comment by IanMeyers** [comment]
Ok. Can you tell me what the s3Prefix entry in the configuration table is? 

Thx,

Ian

**Comment by tomdeblende** [comment]
Sure! How can I tell?

**Comment by IanMeyers** [comment]
In the AWS console switch to dynamodb, and then look at Items in the LambdaBatchLoadConfig table, and there should be one entry for this prefix. 

Ian

**Comment by tomdeblende** [comment]
I was looking there, but it looks to be empty. Which makes sense if I didn't enter one, no?

![image](https://cloud.githubusercontent.com/assets/2959367/12244822/bcb8eec4-b8a5-11e5-81af-a84bcf16a8fc.png)

**Comment by tomdeblende** [comment]
I was looking there, but it looks to be empty. Which makes sense if I didn't enter one, no?

<img width="1168" alt="screen shot 2016-01-11 at 20 54 24" src="https://cloud.githubusercontent.com/assets/2959367/12244869/eb419a70-b8a5-11e5-8ab0-e1bf5c0ba72d.png">

**Comment by IanMeyers** [comment]
Aha! Makes sense then :)

Try running setup.js and then let me know?

**Comment by tomdeblende** [comment]
Do I add a prefix? I thought it was optional?

**Comment by IanMeyers** [comment]
Prefix can be blank, you bet, but you do need a bucket name.

**Comment by tomdeblende** [comment]
The monitoring of the bucket goes OK. If I drop a file, something is triggered.

<img width="646" alt="screen shot 2016-01-11 at 21 00 18" src="https://cloud.githubusercontent.com/assets/2959367/12244960/5e02a9fa-b8a6-11e5-83b0-73a3f2bd5a80.png">

**Comment by IanMeyers** [comment]
Not sure I understand.

**Comment by tomdeblende** [comment]
This is what I ran from the sample directory.

<img width="964" alt="screen shot 2016-01-11 at 21 02 02" src="https://cloud.githubusercontent.com/assets/2959367/12245143/42591b84-b8a7-11e5-9b44-d03bbcc1afba.png">

**Comment by IanMeyers** [comment]
Ah yes I see. That uses a predefined configuration. To use your own, run setup.js instead.

**Comment by tomdeblende** [comment]
But I don't want to use my own :) I just want to have the sample working. It should work like this, no?

**Comment by IanMeyers** [comment]
I'm with you now! On the screenshot you provided before, the bucket should just be the name, not including region and amazonaws.com etc. Try that?

**Comment by tomdeblende** [comment]
Aha! Now we are getting somewhere! At a new error message, so there is progress :)

<img width="1244" alt="screen shot 2016-01-11 at 21 31 01" src="https://cloud.githubusercontent.com/assets/2959367/12245741/b2d81f9c-b8aa-11e5-850d-ed0872a154e4.png">

**Comment by tomdeblende** [comment]
OK, forget that, that was because I reinstalled the code. I still get the same error...

**Comment by IanMeyers** [comment]
Ok. I expect this is because you need to have the handler name 'index.handler' on the lambda function.

**Comment by tomdeblende** [comment]
Yeah, I changed that, and the same error is there...

**Comment by IanMeyers** [comment]
Can you repost the config entry from ddb?

**Comment by tomdeblende** [comment]
Still the same.

<img width="1162" alt="screen shot 2016-01-11 at 21 37 17" src="https://cloud.githubusercontent.com/assets/2959367/12245877/8d3761ac-b8ab-11e5-8714-307444262c6f.png">

**Comment by IanMeyers** [comment]
I have to sign off now due to the time of day. Can you please email meyersi@amazon.com and we'll continue this as soon as you are online tomorrow?

**Comment by tomdeblende** [comment]
will do, thanks Ian! Might be afternoon for me.

**Comment by IanMeyers** [comment]
Issue was to do with a bug in the configSample.js script (now fixed) and the customer environment being on Node 4.x. Have opened up an alternate issue for supporting ES6+ Node version for admin tools.
