### ISSUE TITLE
Cannot read property 'S' of undefined

### ISSUE THREAD

**Issue by jcl9008** [awslabs/aws-lambda-redshift-loader#62]
Having trouble determining where the issues is here.  Cannot read property 'S' of undefined.  The rest of the logs look good - loads the batches, puts them into DynamoDB - loads redshift configuration and then fails.  The batches move to 'locked state'

Any help would be greatly appreciated.

2016-01-14T15:36:24.045Z    901004af-bad4-11e5-bd74-5b6f20d37141    TypeError: Cannot read property 'S' of undefined at /var/task/index.js:904:68 at /var/task/kmsCrypto.js:247:10 at done (/var/task/node_modules/async/lib/async.js:135:19) at /var/task/node_modules/async/lib/async.js:32:16 at /var/task/kmsCrypto.js:242:5 at Response.<anonymous> (/var/task/kmsCrypto.js:202:12) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:353:18) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:595:14)

**Comment by jcl9008** [comment]
Upon further research, it appears that this line is causing the problem - I do have the lambda execution role applied to the function, but it appears to be hitting this (which does exist in DynamoDBs configuration line as an encrypted value:

credentials = 'aws_access_key_id=' + config.accessKeyForS3.S + ';aws_secret_access_key=' + decryptedConfigItems[s3secretKeyMapEntry].toString();

**Comment by IanMeyers** [comment]
Hello,

Thanks for the note, and I"m sure we can get this fixed. Can you tell me if your LambdaRedshiftBatchLoadConfig table entry for the relevant configuration has an entry secretKeyForS3 and it's a string. If so, can you send it to me privately (meyersi@amazon.com) so I can check the format. If it's not there in the table, can you let me know if you have an attribute accessKeyForS3? If you have one but not the other that would be great to know. Also, how did you write the configuration? Did you use setup.js or sample/scripts/configureSample.sh?

Regards,

Ian

**Comment by jcl9008** [comment]
Ian,

Thanks for much for getting back to me personally - much appreciated.  I
was able to 'get around' the issue by setting the access key and secret
using setup.js.  I used the exactly lambda execution policy that was
described in the document and attached it to the lambda function.  It was
able to access the S3 buckets and Dynamo, but I kept running into the error
as soon as Redshift attemtped to access S3 for the copy.  In my first
attempt I used NULL as suggested by the setup.js - which appears to have
put an encrypted in the LoadClusters list map.  Now that I have used the
access key directly, its no longer in the map, and sitting outside of the
map in its own attribute.

I can certainly attempt to recreate the situation - but now that i have it
working I'm in the middle of debugging a rather precarious issue with the
copy that doesn't seem to have a lot of info on it.  My JSON files are
stored as .gz files as I have a lambda function that picks them off the
stream and gzips them up as YYYY/MM/DD/HH/context.requestID.gz  - this all
seems to work great.  But when Redshift executes the batch copy - this
happens:

note the cluster name and bucket name were hidden by me for this email.  I
posted about this to this forum
https://forums.aws.amazon.com/thread.jspa?messageID=696442   but it hasn't
been touched by an amazon rep in quite some time - but ironically someone
else ran into the issue a few days ago.

"clusterLoadStatus": {
    "S":
"{\"redshift-cluster-name-hidden\":{\"status\":-1,\"error\":{\"name\":\"error\",\"length\":345,\"severity\":\"ERROR\",\"code\":\"XX000\",\"detail\":\"\n
 -----------------------------------------------\n  error:  non-std
exception\n  code:      1009\n  context:   unknown\n  query:     1719\n
 location:  unknown:-1\n  process:   padbmaster [pid=3974]\n
 -----------------------------------------------\n\",\"file\":\"/home/awsrsqa/padb/src/sys/xen_execute.cpp\",\"line\":\"6060\",\"routine\":\"pg_throw\"}}}"
  },
  "entries": {
    "SS": [

"bucketnamehidden/2016/01/14/16/b9208533-d29b-45a6-a06b-8f67f11f0e38.gz",

"bucketnamehidden/2016/01/14/16/f345c6b2-0d2a-44ea-a6ab-dc159ec77c84.gz",

"bucketnamehidden/2016/01/14/16/f529b5a7-48c0-4446-9b30-68ba1816a231.gz"
    ]
  },

The contents of a S3 file is similar to this JSON:

{"iid":"14527910375262e385fd8364aeac410f","time":1452791038,"acc":246,"adv":101,"cid":352,"pid":2165,"vid":1,"ut":"RM","up":0.0,"tz":"America\/Los_Angeles","br":"Firefox","brv":47,"os":"OS
X","ref":"www.blue.com","ip":"10.0.0.218","type":"serve_impression","dat":"{}","cb":1452791132253,"host":"dev001","ua":"Mozilla\/5.0
(Macintosh; Intel Mac OS X 10_11_1) AppleWebKit\/537.36 (KHTML, like Gecko)
Chrome\/47.0.2526.106 Safari\/537.36"}

**Comment by jcl9008** [comment]
I don't know if I am on the right path or not, but I specified JSON as the
format the data was in - should I be specifing GZIP, or JSON and then
typing GZIP in the additional copy options?

**Comment by IanMeyers** [comment]
Hi,

Glad to hear you are making progress, and yes - let's circle back round to the setup issue when the time is right. Regarding the data format, you should specify a data type of 'JSON' in the running of setup.js, and if you are happy to use JSON auto then you can leave the jsonPath entry empty. Have a review of http://docs.aws.amazon.com/redshift/latest/dg/copy-usage_notes-copy-from-json.html for more details on loading JSON data. Then you would add option GZIP to the copyOptions entry, plus other options as outlined in http://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-source-s3.html#copy-parameters-data-source-s3-optional-parms.

Do let me know how it goes.

Ian

**Comment by jcl9008** [comment]
Hi Ian -

Thanks for letting me contact you directly!  I configured it as JSON with
the additional copy option of GZIP - and I still get the following error
messages in CloudWatch:

Cluster Load Failure error: non-std exception on Cluster
adv-analytics.cm5s3jrjhig9.us-east-1.redshift.amazonaws.com

I just cant find any documentation on this particular error message, and
everything about it is "undefined" or "unknown" ;-)

2016-01-14 18:30:45 UTC
2016-01-14T18:30:45.728Z ec28e7ac-baec-11e5-892f-2515d0aa7853 Linked
Manifest manifest-2016-01-14-18:30:45-2600 to Batch
92369009-93ba-4316-a2c1-735557f66fd6
2016-01-14 18:30:45 UTC
2016-01-14T18:30:45.863Z ec28e7ac-baec-11e5-892f-2515d0aa7853 Connecting to
Database <<database hidden>>:5439
2016-01-14 18:30:46 UTC
2016-01-14T18:30:46.406Z ec28e7ac-baec-11e5-892f-2515d0aa7853 Cluster Load
Failure error: non-std exception on Cluster
<<database hidden>>
2016-01-14 18:30:46 UTC
2016-01-14T18:30:46.470Z ec28e7ac-baec-11e5-892f-2515d0aa7853 { '
<<database hidden>>: { status: -1,
error: { [error: non-std exception] name: 'error', length: 345, severity:
'ERROR', code: 'XX000', detail: '\n
-----------------------------------------------\n error: non-std
exception\n code: 1009\n context: unknown\n query: 1917\n location:
unknown:-1\n process: padbmaster [pid=8557]\n
-----------------------------------------------\n', hint: undefined,
position: undefined, internalPosition: undefined, internalQuery: undefined,
where: undefined, schema: undefined, table: undefined, column: undefined,
dataType: undefined, constraint: undefined, file:
'/home/awsrsqa/padb/src/sys/xen_execute.cpp', line: '6060', routine:
'pg_throw' } } }

**Comment by IanMeyers** [comment]
So because this error is being thrown by padbmaster, the COPY command is getting to the database and then failing. Redshift can load flat JSON data which contains scalar values. Assuming that you are using 'JSON auto', I'm wondering if the "dat" attribute is the issue. It's cited in the example as '{}', which would be interpreted by the loader as an empty object, but would also cause the load to fail. You should get a better error of course, but just wondering if you could create a single line file with some sample data, and inject that to see if it's a data problem or some missing option in the COPY command? You can also just start by directly loading the data with a manual COPY command in Redshift, on a candidate file - if this works then it should also work through the Lambda loader.

Ian
