### ISSUE TITLE
Age-based trigger for batches not working?

### ISSUE THREAD

**Issue by jklukas** [awslabs/aws-lambda-redshift-loader#69]
In testing the loader, I'm noticing that loads are never triggered due to batch age (I've configured the `batchTimeoutSecs` to the minimum of 120 seconds) but always due to reaching the max batch size.

I added in some debug statements to see what was going on, and I saw that `(common.now() - lastUpdateTime)` is always on order `0.3`.

I believe there's a logic error here. Whenever the function runs, [`lastUpdate` gets set to `common.now()` in `addFileToPendingBatch`](https://github.com/awslabs/aws-lambda-redshift-loader/blob/0ade265462059e946319082318996f8ea2dbf185/index.js#L304) which runs **before** the `processPendingBatch` logic where the age of the batch is checked.

I had assumed that the `batchTimeoutSecs` check would be based on the total age of the batch. Any new batch entry that comes in after `batchTimeoutSecs` from the creation of the batch would trigger a load. Am I misunderstanding the design?

**Comment by IanMeyers** [comment]
Hello,

No, I can see where you are coming from. This feature is currently set up to address when we have long pauses between multiple files, rather than saying 'regardless of file count, load every N seconds'. Put another way, the batchTimeoutSecs is implemented as 'perform a load if there's a gap of batchTimeoutSecs between files'.

What do you think? Would it make more sense to trigger this from the batchCreatedDate?

Ian

**Comment by jklukas** [comment]
`What do you think? Would it make more sense to trigger this from the batchCreatedDate?`

Yes, that's what I expected and it's the number I care about operationally.

We currently use a homegrown service for batching streaming events to S3, and then grouping those together into loads to Redshift. We perform loads to each table at minimum every 15 minutes. This lets us give a fairly definitive answer to the common question from analysts: "What's the latency for data to get into Redshift?" It's important to us to be able to give a reasonably correct upper bound for latency (assuming our cluster is operating normally and able to keep up with load requests from a performance perspective).

Triggering based on `batchCreatedDate` would allow us to provide such a guarantee with the Lambda Loader.

**Comment by IanMeyers** [comment]
OK - I'll have a look at how this could be done.

**Comment by jklukas** [comment]
I'm also concerned that the "Ensuring Loads happen every N minutes" section of the docs is misleading. Based on my understanding of the current logic, if you do have new files trickling in every few minutes, adding a scheduled job to create trigger files won't have any effect.

For context, we have a cluster with 64 slices, so we ideally want 64 files in each batch. We write new files at least once a minute, but that still could lead to a lag of an hour (a minute \* 64) before a load is triggered.

**Comment by jklukas** [comment]
> OK - I'll have a look at how this could be done.

Excellent!

**Comment by IanMeyers** [comment]
Understand the point about docs - will revisit when I have figured a path forward.

**Comment by IanMeyers** [comment]
This is now fixed in 2.3.0. Each time a file is added to a batch, a new attribute `writeDates` is appended to indicating the dates that files were added. The `batchTimeoutSecs` is then calculated from the earliest write date for the batch, rather than the last update date.

**Comment by jklukas** [comment]
I deployed 2.3.0 into our environment where we're testing. I haven't inspected the behavior in much depth, but I do see in the logs that we are now seeing age-based loads. And your description of the implementation seems entirely in line with what I was expecting.

Thanks for implementing this!
