### ISSUE TITLE
jdbc?

### ISSUE THREAD

**Issue by kessler** [awslabs/aws-lambda-redshift-loader#7]
Why connect with jdbc to redshift?

Any particular reason why you don't use https://github.com/brianc/node-postgres to connect to redshift (or other node alternatives) ?

**Comment by IanMeyers** [comment]
Not in particular. Is there some reason you'd prefer an alternative library?

**Comment by kessler** [comment]
Well, just trying to understand if there was a special motive to load a jvm and use jdbc instead of a js/native driver. maybe some special features that redshift has that are not supported by js/native implementations etc...

**Comment by IanMeyers** [comment]
Thanks for the suggestion. I'll look into this.

**Comment by IanMeyers** [comment]
This will be migrated to use the node postgres library in version 2.x.
