### ISSUE TITLE
Recommended Lambda memory size?

### ISSUE THREAD

**Issue by zeman** [awslabs/aws-lambda-redshift-loader#70]
I see the readme suggests using the max timeout for a function but are there any recommendations about how much memory to allocate. If the function is just waiting for the COPY command to finish does it need much memory at all? Is there any relationship between the size of the data being processed and the Lambda memory?

**Comment by IanMeyers** [comment]
I see my function using < 20MB of memory. If you have a batch size that is very large, then you would probably need to increase the memory, as the file list in the batch will take up space.
