### ISSUE TITLE
Question: AWS-Lambda-Redshift-Loader vs Amazon Kinesis Firehose

### ISSUE THREAD

**Issue by RAbraham** [awslabs/aws-lambda-redshift-loader#71]
Hi,
I was wondering if you could elaborate more on the following piece of documentation:

>  "For automated delivery of streaming data to S3 and subsequently to Redshift, also consider using Amazon Kinesis Firehose."

I consider your project to be an automation tool as well :). Do you mean that we have manage the instances on which your code runs? or are there other points?

Thanks,
Rajiv

**Comment by jklukas** [comment]
Here's my understanding of the fundamental difference.

With the Lambda Loader, you're responsible for getting files to S3. So if your source data is streaming, you're going to handle batching that data.

Kinesis Firehose takes in a stream of records and handles that batching step for you in addition to the Redshift loading. I wouldn't be surprised if Firehose uses the Lambda Loader behind the scenes for the Redshift loading step.

**Comment by gdelgado** [comment]
The way I understand it is that if your existing client code is already
taking advantage of an existing Kinesis stream you should use the Lambda
Loader. If your in the process of building your client code or are planning
to update your client code and will be pushing your data to S3 or a
Redshift table then go the Kinesis Firehose route.

**Comment by IanMeyers** [comment]
Firehose is designed to support delivery of streaming data to s3 and Redshift, while this tool is designed to facilitate loading file data automatically as it appears in S3. Firehose would be the right solution for consuming Streams and implementing an archival process, but if you just want to take advantage of an existing file feed, then this module may be helpful.
