### ISSUE TITLE
records being pushed to table in default schema instead of specified schema  

### ISSUE THREAD

**Issue by myali05** [awslabs/aws-lambda-redshift-loader#76]
Hi,

I am using the lambda redshift loader to push records from S3 into redshift (I am getting records through firehose into S3). The issue I was running into was that the lambda redshift loader was trying to load into the default schema instead of the database specified in the configuration. I was able to deploy a modified version of the loader with the change mentioned below to get it to work correctly... but not sure if this is really a bug or if I am not using the loader correctly.

index/js: Line 922 => 
`
copyCommand = copyCommand + 'begin;\nCOPY ' + clusterInfo.targetTable.S + ' (' + clusterInfo.columnList.S + ') from \'s3://'
                                            + manifestInfo.manifestPath + '\'';
`

to : 
`copyCommand = copyCommand + 'begin;\nCOPY ' + clusterInfo.clusterDB.S + '.' + clusterInfo.targetTable.S + ' (' + clusterInfo.columnList.S + ') from \'s3://'
                                            + manifestInfo.manifestPath + '\'';`

Thanks,
Mir Ali

**Comment by IanMeyers** [comment]
Hello,

Cross database operations are not supported on Redshift, so unfortunately this is working as expected.

Ian
