### ISSUE TITLE
README/documentation is out of date

### ISSUE THREAD

**Issue by Rio517** [awslabs/aws-lambda-redshift-loader#84]
Hi, 

As I'm working through getting this set up, I'm noticing the documentation in the readme needs some minor updates. In particular, it seems like the [security setup instructions](https://github.com/awslabs/aws-lambda-redshift-loader/blame/master/README.md#L65) are only valid in EC2-classic, which are [no longer supported](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Introduction.html#what-is-supported-platform) for new accounts.  Info for clusters in VPCs are missing.

I'm working on this now [here](https://github.com/Rio517/aws-lambda-redshift-loader/tree/mf-update-documentation), and I'll send a pull request when I think I have it.

**Comment by IanMeyers** [comment]
Hello,

Happy to take any doc updates that you think add clarity. That specific line could be updated to be 'Cluster Security Group or VPC Security Group', but the rest of the instructions are still correct unless you are using the Lambda VPC endpoints. We can definitely use a doc update for the use of VPC endpoints!.

Thx,

Ian

**Comment by Rio517** [comment]
Odd.  That is not what I'm seeing, actually.  The instructions say:

```
1. Log in to the Amazon Redshift console.
2. Select Security in the navigation pane on the left.
3. Choose the cluster security group in which your cluster is configured.
4. Add a new Connection Type of CIDR/IP and enter the value 0.0.0.0/0.
5. Select Authorize to save your changes.
```

Those seem to be invalid, at least when I'm looking at My VPC Dashboard > Security > Security Group. Here is the edit panel when I have a security group selected:  

![2016 04 30_redshift_cluster_security_group_edit](https://cloud.githubusercontent.com/assets/14241/14681473/88667ac2-0721-11e6-8fce-9a98ca196d84.png)

If one does click "Edit," and then "Inbound" or "Outbound," then "Edit", then "Add Rule ", there is no "CIDR/IP" rule type.  Perhaps the old instructions are still valid for "Cluster Security Group", but since I have a newer account I cannot see those options. 

I am not sure what I should be doing and was going to be testing different options to see what works.  Am I missing something or looking in the wrong place?  I am brand new to Redshift/VPC settings.

**Comment by ghost** [comment]
Working on this as well and new to Redshift so I'm a bit stuck... Hope to get some answers to this soon!

**Comment by Rio517** [comment]
@jdmaresco  I've got things working on my end. I'm in the process of documenting my steps. I should be done by early afternoon EST on Friday 8/22 and will submit a pull request w/ updated documentation.  I'll ping you when I have it up.

**Comment by beaucronin** [comment]
👍  up against this too

**Comment by Rio517** [comment]
I haven't quite had time to get back to this, but am putting together a guide for a friend's company that you could use if you're stuck.  http://rio517.github.io/slate/#controlshift-to-redshift-pipeline

I still have a few [issues](https://github.com/Rio517/slate/issues/1) to sort out, before finalizing, but it should get you most of the way there.

**Comment by IanMeyers** [comment]
I'm happy to update the documentation, but if you guys are quite far along on documentation I don't want to undo your good work or cause a big merge issue.

**Comment by Rio517** [comment]
I have a bit ready to go and I'll submit a pull request later today.

**Comment by IanMeyers** [comment]
OK - I am also building out very robust documentation for this, so if you are OK with it I'll cherry pick your comments that will be useful in the documentation, but probably not merge your PR as it will be quite a big job (I'm adding diagrams etc).

**Comment by IanMeyers** [comment]
Added my commit - please feel free to give feedback through this Issue.

**Comment by Rio517** [comment]
Sounds good.  Things I'd especially mention: 
- I think it would help users to be more explicit that they have to connect to redshift and create their DB and schema with the proper permissions.   Specifically, if users are truncating, then it seems the DB user has to own the table.  Just granting insert permissions was not enough.
- It would be nice to explain what the purpose of providing column headers accomplishes.

**Comment by IanMeyers** [comment]
For the first one, I've assumed that the cluster has already been configured with a data model, and will review the statements made about permissions for the user who performs the database load.

For the second one, I've added documentation for the Column List setup option.
