### ISSUE TITLE
truncateTarget DynamoDB column seems to have no effect

### ISSUE THREAD

**Issue by benburkhart1** [awslabs/aws-lambda-redshift-loader#85]
Here you set a 'truncateTarget' column in the DynamoDB record here:
https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/setup.js#L29-31

and then you set it in the cluster options later on:
https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/setup.js#L202-L209

This appears to be unused everywhere except during upgrades (I assume it was where you originally stored this and then later migrated it to the cluster options). 

Is there a reason this old record-level truncateTarget should exist? Might be confusing to devs. Not a major gripe.

**Comment by IanMeyers** [comment]
Yep good point - can be removed. Will do so.

**Comment by IanMeyers** [comment]
dunno why it was left over tbh

**Comment by IanMeyers** [comment]
Done
