### ISSUE TITLE
More Secure Means of Lambda<>Redshift Connecting

### ISSUE THREAD

**Issue by Rio517** [awslabs/aws-lambda-redshift-loader#86]
Hi, 

Is there a more secure way of allowing my Lambda instance to load data into my Redshift cluster than by adding CIDR of `0.0.0.0/0`?  I'd love to make it more restrictive.

**What I've Tried:** My Redshift Cluster is in a VPC (only option available to my account).  I added my Lambda to the same VPC as my Redshift Cluster. I added the policies AmazonRedshiftFullAccess and AmazonDMSRedshiftS3Role to my lambda's IAM role. I had also updated my IAM's role to the policy described below.  

Any help would be appreciated. Thanks!

---

**My Current Role Policy:**

``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1424787824000",
            "Effect": "Allow",
            "Action": [
                "dynamodb:DeleteItem",
                "dynamodb:DescribeTable",
                "dynamodb:GetItem",
                "dynamodb:ListTables",
                "dynamodb:PutItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:UpdateItem",
                "sns:GetEndpointAttributes",
                "sns:GetSubscriptionAttributes",
                "sns:GetTopicAttributes",
                "sns:ListTopics",
                "sns:Publish",
                "sns:Subscribe",
                "sns:Unsubscribe",
                "s3:Get*",
                "s3:Put*",
                "s3:List*",
                "kms:Decrypt",
                "kms:DescribeKey",
                "kms:GetKeyPolicy"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DetachNetworkInterface",
                "ec2:DeleteNetworkInterface"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by IanMeyers** [comment]
Sure - from where you are, the last step will be to enable connections on the Redshift port number that you've selected for your cluster from the cluster VPC Security Group, to the security group that you are using for your Lambda function.

To do this, go to your Redshift cluster, and click on the link next to 'VPC Security Groups'. Then for this VPC Security Group that is opened, on the bottom select the 'Inbound' tab, and click 'Edit'. Then click 'Add Rule', Type = Redshift, select the correct port number for your cluster, Source = Custom IP, and then type the name of the AWS Lambda Function Security Group.

**Comment by Rio517** [comment]
Perfect. Thanks.
