### ISSUE TITLE
No Configuration Found

### ISSUE THREAD

**Issue by mbalog** [awslabs/aws-lambda-redshift-loader#87]
After setting up and having the redshift-loader and successfully running for a bit, I see this error:
"No Configuration Found for <bucket name>/<prefix>.  My example I setup the s3Prefix to be: 
cw.rs/input/log_files

Nothing has changed in my config.  I was able to fix this by deleting the lambda and recreating it, with the exact same settings.  Has anyone else seen this?

**Comment by IanMeyers** [comment]
That's not something I've had reported before. '/' isn't a valid configuration as it doesn't include a bucket name, which would never be sent to Lambda in the first place. Can you send an example of the file that was causing this to happen?

**Comment by mbalog** [comment]
I don't have the log file anymore for this. What I saw was the Lambda not returning from the DynamoDB call from the AWS sdk. The exact error was:

2016-04-21T18:08:35.399Z    dxxxxxxxxxx31   No Configuration Found for cw.rs/input/log_files

Even though there was a match in DynamoDB.  It seemed that the Lambda just stopped talking to DynamoDB.  So when this happened again I just went to the Lambda Management Console and hit "Publish new Version" for that Lambda.  Then it started working again.

**Comment by IanMeyers** [comment]
There is a known issue with the AWS SDK used in this project and the Node.js 4.x runtime. Can you please ensure that your Lambda language version is set to Node.js 0.10?

**Comment by peetasan** [comment]
Has the above mentioned known issue been addressed? Node.js 0.10 is being deprecated on AWS lambda, and we'll need to upgrade soon. Thanks,

**Comment by IanMeyers** [comment]
I believe that this issue has been resolved in later versions of the SDK. We have no issues reported with the platform running on Node 4.x
