### ISSUE TITLE
Support for loading data into Redshift cluster running within a Dedicated VPC

### ISSUE THREAD

**Issue by FrancisLau-Smartsheet** [awslabs/aws-lambda-redshift-loader#89]
Does this lambda loader support for loading data into Redshift cluster running within a Dedicated VPC? 

AWS [Lambda documentation ](http://docs.aws.amazon.com/lambda/latest/dg/vpc.html)says "AWS Lambda does not support connecting to resources within Dedicated Tenancy VPCs. For more information, see Dedicated VPCs."

However, since the Loader Lambda executes copy commands, we think it might work. I just want to reach out to see if there are any known issues with Redshift clusters running within a Dedicated VPC and also to get your thoughts.

Thanks

**Comment by IanMeyers** [comment]
From a connectivity perspective it should be possible, but AWS Lambda cannot be run within a dedicated tenancy VPC, so you would have to use VPC peering and enable connections to Redshift on the basis of the peered VPC, which may or may not be acceptable.
