### ISSUE TITLE
Auto unlocking

### ISSUE THREAD

**Issue by malaqueueit** [awslabs/aws-lambda-redshift-loader#96]
Hi

As we are adding more and more files we more frequently experience locked batches. When there is a locked batch the dynamo write usage on the LambdaRedshiftBatches table spikes to an extreme. 

Is there any way to avoid locked batches or to auto unlock them?

**Comment by IanMeyers** [comment]
I'd suggest increasing the batch size and/or the timeoutSeconds, so that you switch batches less frequently. Today there's no auto-unlock, as you should see the loader rotate onto a free batch very quickly

**Comment by IanMeyers** [comment]
Did increasing the batch size help at all?

**Comment by malaqueueit** [comment]
I did help to increase the batch size. Locks are less frequent. Is there any way to get a notification when a lock happens?

**Comment by IanMeyers** [comment]
You will get a notification if a new file is unable to acquire a reference to an open batch in 100 attempts. If this occurs and you have configured a failureTopicARN, then you will get a notification.
