### ISSUE TITLE
[QUESTION] AWS Lamda Timeouts?

### ISSUE THREAD

**Issue by tspicer** [awslabs/aws-lambda-redshift-loader#98]
Before jumping in, would love to understand the viability for uses cases that exceed the 300 second limit for lambda. Is the 300 sec lambda an issue for people? If so, how are people accommodating long COPY times, say 10+ minutes? Appreciate feedback for this use case.

**Comment by IanMeyers** [comment]
Would be good to know how many files will be loaded in that 10 minute copy time. In many cases if you have a large number of files, then you can just reduce the batch count to stay within the 5 minute timeout. If you only have 1-2 files, this will take longer than if you have an even multiple of files per CPU.

**Comment by tspicer** [comment]
The amount of files will vary, it might be one or handful. We do not have a lot of control over the inbound volume, so actual counts for a given manifest will vary. 

Lets assume we can optimize a few things to minimize risk. However, there are cases where the limit is exceeded. In the current implementation what happens when the lambda limit is exceeded?

**Comment by IanMeyers** [comment]
Unfortunately the batch will be marked as 'error' and will have to be reprocessed. Because of this, it's important to set the file count/timeout settings based what you observe in terms of 'typical' volume.

**Comment by IanMeyers** [comment]
Also - please note that version 2.4.2 adds support for a batchSizeBytes based processing, so that you can ensure that every N bytes you process the input files, regardless of how many of them there are.

**Comment by IanMeyers** [comment]
Closing this now but please re-open if needed.
